### ISSUE TITLE
focus is losing by moving the mouse

### ISSUE THREAD

**Issue by bugmelder** [rzander/sccmclictr#10]
By moving the mouse after clicking into the text field "target computer" or "connection options" the focus of the text field is lost.
In "Agent Settings" there is no such behaviour, all works like expected.

**Comment by rzander** [comment]
The Navigation Pane and Ribbon is an external Control... not sure if we can fix this. Will check that.

**Comment by rzander** [comment]
i think, I was able to fix (or improve it)...

**Comment by SCCMAdmin** [comment]
I'd like to help confirmation that this issue is resolved. I've had a pain with this in an old version. About to try 1.0.3.5 for starters.

**Comment by rzander** [comment]
I just want to test and confirm that the App uninstall is workin.. then v1.0.3.6 will be released.. (expect next week)

**Comment by rzander** [comment]
If you want to test the change, update the existing files with:
[v1.0.3.6_preview.zip](https://github.com/rzander/sccmclictr/files/1116233/v1.0.3.6_preview.zip)

**Comment by SCCMAdmin** [comment]
I've been using 1.0.3.6 this week and never had the annoying issue where the panel disappears. Great work @rzander !
