### ISSUE TITLE
Application has green flag despite not being installed/Failed Deployment

### ISSUE THREAD

**Issue by drewmilizia** [rzander/sccmclictr#101]
On the Applications screen I am seeing a green flag even if the deployment failed and the software has not been installed.

v1.0.5
![2019-03-25_12-53-24](https://user-images.githubusercontent.com/10358267/54938861-9b420b80-4efd-11e9-85fc-edc0fae51b6d.png)

Thanks!

**Comment by rzander** [comment]
The green Flag has nothing to do with the InstallState. It's an indicator if the deployment is a simulated or real deploymnet.... Should we change the Icon to something else ?

**Comment by drewmilizia** [comment]
Oh I see, sorry about that.  I was going with how the Programs were deployed with the flag indicating success or fail.  I am getting older and more easily confused!  HAHA

**Comment by newwolf** [comment]
> 
> 
> The green Flag has nothing to do with the InstallState. It's an indicator if the deployment is a simulated or real deploymnet.... Should we change the Icon to something else ?

Well whats the point of it?
Because I also saw a "smiley with glasses" like icon but didn't understand it.
Maybe a option to at a ALT-text/toast-box to it?
It's just a idea?!?!
