### ISSUE TITLE
Some more scripts for you..

### ISSUE THREAD

**Issue by russr123** [rzander/sccmclictr#102]
i have 4 more scripts you can add to the "DO" folder,  attached...

- SCCM-ResetRebootCountdown.ps1
- SCCM-ChangeForcedReboot2Non-forced.ps1
- SCCM-CANCELPendingReboot.ps1
- SCCM-RebootWithTimer.ps1

[DO.zip](https://github.com/rzander/sccmclictr/files/3177606/DO.zip)

For more info on how they work, see my Blog post https://sccmf12twice.com/2019/05/sccm-reboot-decoded-how-to-make-a-pc-cancel-start-extend-or-change-mandatory-reboot-to-non-mandatory-on-the-fly/

**Comment by rzander** [comment]
Thanks, will add these files to V1.0.5.2...

**Comment by rzander** [comment]
Preview MSI: https://github.com/rzander/sccmclictr/releases/tag/1.0.5.2

**Comment by russr123** [comment]
can you edit the reboot cancel script to this?
#CANCEL a pending rebootRemove-Item -path 'HKLM:\SOFTWARE\Microsoft\SMS\Mobile Client\Reboot Management\RebootData';Remove-Item -path 'HKLM:\SOFTWARE\Microsoft\SMS\Mobile Client\Updates Management\Handler\UpdatesRebootStatus\*';Remove-ItemProperty -name * -path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired';#on PS2.0, "Remove-ItemProperty" doesn't work, so use this.#Remove-Item -path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired';shutdown -a Restart-Service ccmexec -force
    On Tuesday, May 14, 2019, 2:07:36 PM EDT, Roger Zander <notifications@github.com> wrote:  
 
 
Closed #102.

**Comment by rzander** [comment]
Should it look like this ? https://github.com/rzander/sccmclictr/blob/master/Plugins/Plugin_PSScripts/PSScripts/DO/SCCM-CANCELPendingReboot.ps1

**Comment by russr123** [comment]
yes, perfect...
    On Thursday, May 16, 2019, 2:10:20 PM EDT, Roger Zander <notifications@github.com> wrote:  
 
 
Should it look like this ? https://github.com/rzander/sccmclictr/blob/master/Plugins/Plugin_PSScripts/PSScripts/DO/SCCM-CANCELPendingReboot.ps1
