### ISSUE TITLE
Command line switches?

### ISSUE THREAD

**Issue by arjohnson77** [rzander/sccmclictr#104]
Are there any command line switches available? I'm looking to combine this tool with another 3rd party tool (mRemoteNG), which allows for running external tools, including a path and argument list. It would be handy if I could pass through the computer name and credentials to SCCMCliCtr (so SCCMCliCtr would open automatically connected to the specified computer with the specified credentials, etc.)

**Comment by rzander** [comment]
The following Parameters are available: 
`sccmclictrwpf.exe <Hostname> [/Username:xxxx] [/Password:xxxxxx] [/RegisterConsole] [/UnRegisterConsole]`
