### ISSUE TITLE
How to Export Overview tables?

### ISSUE THREAD

**Issue by ACE350** [rzander/sccmclictr#108]
I am trying to gather the "All Updates" table of information per stage of a build of a new image. Normally I would just run a "Get-wmiobject" or "Get-ciminstance" and pipe to a table, but I want all the info that will not fit in the output. sccmclictr outputs exactly like I need/want. I cannot figure out how to capture that output or export it. If I highlight anything in the table (Inventory > Overview > All Updates) and copy (Ctrl-C) even one line, the application incurred a fatal error. I am sorry if I am missing an included feature. 
This is a great product (that's why I donated) that allows me to be more dangerous/resourceful than a nuub should be.

**Comment by rzander** [comment]
I can select one or multiple items in "All Updates" and ctrl+c to copy the content without Problems...

If you open "All Updates" you get the PowerShell Code that is used to get the updates in to footer of the tool:
 ```get-wmiobject -query "SELECT * FROM CCM_UpdateStatus" -namespace "root\ccm\SoftwareUpdates\UpdatesStore"``` 
to get the result in in a gridview just run  ```get-wmiobject -query "SELECT * FROM CCM_UpdateStatus" -namespace "root\ccm\SoftwareUpdates\UpdatesStore" | ogv```
