### ISSUE TITLE
Application Uninstall is not working

### ISSUE THREAD

**Issue by bugmelder** [rzander/sccmclictr#11]
In Software Distribution with the right click on an Application there is the menu entry "Uninstall".
With several Applications it doesnt work.
Install is working.

**Comment by Xento** [comment]
I had the same issue.
For me it is fixed with this codechange:
https://github.com/rzander/sccmclictrlib/pull/1

**Comment by rzander** [comment]
I have to check that... give me some time...

**Comment by rzander** [comment]
Fix is implemented in V1.0.3.6. The fix allows to uninstall required Applications. Required Apps will be reinstalled with the next application Evaluation cycle. So this is just an option for troubleshooting.
