### ISSUE TITLE
Log Monitoring doesnt work

### ISSUE THREAD

**Issue by bugmelder** [rzander/sccmclictr#12]
The Log Monitoring Feature doesnt work.
Neither "Select Files:" nor "Read Logs" does something.

**Comment by rzander** [comment]
What's you PowerShell Version ? I never had Problems, but I've heard from others that they have the same Issues...

**Comment by bugmelder** [comment]
PS P:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

**Comment by rzander** [comment]
PowerShell 4 is also a requirement on the Client side..

**Comment by rzander** [comment]
Will close this Issue as PowerShell V4 is a requirement.
