### ISSUE TITLE
missing icons in Pending Updates - EvaluationState

### ISSUE THREAD

**Issue by primarijus** [rzander/sccmclictr#123]
instead icons I have text like ciJobStateWaitInstall

**Comment by primarijus** [comment]
![image](https://user-images.githubusercontent.com/11484808/64857715-9eed5a00-d625-11e9-84f3-3ad4f35ceb0d.png)

**Comment by rzander** [comment]
That's by design... But I agree that for visibility the prefix "ciJobState" can be removed from the EvauluationState.

**Comment by primarijus** [comment]
old versions have red/green/yellow icons 
icons a better to understand

**Comment by pilgi3** [comment]
Will we see the icons again in an upcoming release?

**Comment by rzander** [comment]
What kind of Icons would you like to sse ? There are many options:
```
  ciJobStateNone,  
  ciJobStateAvailable,  
  ciJobStateSubmitted,  
  ciJobStateDetecting,  
  ciJobStateDownloadingCIDef,  
  ciJobStateDownloadingSdmPkg,  
  ciJobStatePreDownload,  
  ciJobStateDownloading,  
  ciJobStateWaitInstall,  
  ciJobStateInstalling,  
  ciJobStatePendingSoftReboot,  
  ciJobStatePendingHardReboot,  
  ciJobStateWaitReboot,  
  ciJobStateVerifying,  
  ciJobStateInstallComplete,  
  ciJobStateError,  
  ciJobStateWaitServiceWindow  
```

**Comment by primarijus** [comment]
some of this 
tnx

ciJobStateAvailable,  
ciJobStateDownloading,  
ciJobStateWaitInstall,  
ciJobStateInstalling,  
ciJobStatePendingSoftReboot,  
ciJobStatePendingHardReboot,  
ciJobStateWaitReboot,  
ciJobStateVerifying,  
ciJobStateInstallComplete,

**Comment by rzander** [comment]
[Preview.zip](https://github.com/rzander/sccmclictr/files/3725713/Preview.zip)
... just implemented the code from the previous version.
All available Icons are here: https://github.com/rzander/sccmclictr/tree/master/SCCMCliCtrWPF/SCCMCliCtrWPF/Images

My test clients did not had any pending updates :-( . If you can give feedback from clients with different states if makes sense or not... Just replace the existing files with the files from the preview.zip

**Comment by primarijus** [comment]
works like a charm
