### ISSUE TITLE
Open Console PS does not work for ssl

### ISSUE THREAD

**Issue by claus66** [rzander/sccmclictr#124]
There's a bracket too much in mainPage.xaml.cs in line 805:

Explorer.StartInfo.Arguments = @"-NoExit -Command " + sCred + sPS + " -UseSSL -Credential $creds)";

Should be:

Explorer.StartInfo.Arguments = @"-NoExit -Command " + sCred + sPS + " -UseSSL -Credential $creds";

Regards,
Claus

**Comment by rzander** [comment]
The current Version of this code section looks different.. Are you referencing an old Version ?

**Comment by claus66** [comment]
The code might be from an earlier version but error is there in v. 1.5.0.3

**Comment by rzander** [comment]
Do you get an error message ? if yes, can you post the message...

**Comment by claus66** [comment]
Hi Roger
Sorry for the inconvenience. I had mixed up versions and can confirm that it works in 1.5.0.3

Thanks,
Claus
