### ISSUE TITLE
Notify-UserOfReboot not working

### ISSUE THREAD

**Issue by pilgi3** [rzander/sccmclictr#127]
When i connected and click "Notify-UserOfReboot" the Client Center hangs.
The client get no message!
![image](https://user-images.githubusercontent.com/44865075/65515276-48163900-dedf-11e9-8c95-4afca6ebdd5e.png)

**Comment by russr123** [comment]
this is the basis for the script,
https://www.itninja.com/blog/view/reboot-required-toast-notifications-for-windows-machines

the thing is, if you open a PS window and paste it in a run it, it works, every time i try to get it to run any other way, it wont.

**Comment by pilgi3** [comment]
I tried on my test clients and yes you are right. Works local but not remote ...

**Comment by rzander** [comment]
changed it to: 
```PowerShell
Set-Location (Get-ItemProperty("HKLM:\SOFTWARE\Microsoft\SMS\Client\Configuration\Client Properties")).$("Local SMS Path")
.\SCToastNotification.exe "Notice: Pending Reboot Needed" "Your PC Needs to restart as soon as you can."
msg * "Notice: Pending Reboot Needed...." "Your PC Needs to restart as soon as you can."
```
