### ISSUE TITLE
Start der App dauert (wegen Internet Verbindung?)

### ISSUE THREAD

**Issue by horst789github** [rzander/sccmclictr#128]
wenn ich Client Center starte, dauert es relativ lange (10-20 sekunden) bis die App dann offen ist. Auf dem Resourcen Monitor sehe ich dass er versucht eine Homepage/IP zuerreichen (Software Update Check?) und da die Firewall bei uns alles blockt, wartet er hier bestimmt bis er in einen timeout läuft?

Kann man das irgendwie beheben, für umgebungen wo es kein Internet gibt? z.b. beim start gar nichts abfragen und einfach starten lassen und erst wenn die app offen ein update check machen (wenn der nutzer das den einstellungen eingestellt hat).

**Comment by rzander** [comment]
Durch löschen der Datei "Plugin_SelfUpdate.dll" wird der Update-Check verhindert.
In den meisten mir bekannten Fällen liegt es jedoch am prüfen der File-Signaturen. Wenn z.B. CRL (Certificate Revocation List) checking aktiviert ist, versucht Windows den CRL Server der Signierten Dateien zu erreichen (http://crl.comodoca.com/COMODORSACodeSigningCA.crl
) um zu prüfen, ob das Zertifikat noch gültig ist. Da es einige Dateien (Plugin*.dll) sind, kann das ein Moment dauern. Werden die Signature denn als "Vertrauenswürdig" erkannt ?

**Comment by horst789github** [comment]
> ) um zu prüfen, ob das Zertifikat noch gültig ist. Da es einige Dateien (Plugin*.dll) sind, kann das ein Moment dauern. Werden die Signature denn als "Vertrauenswürdig" erkannt ?
"The timestamp signature and/or certificate could not be verified or is malformed" also sieht so aus, als wäre es die Cert überprüfung...

**Comment by rzander** [comment]
Anbei eine Liste mit den Plugins:
https://github.com/rzander/sccmclictr/wiki/3)-Installation#plugins
Wenn keine Spende getäigt wurde und kein Internet zu Verfügung steht, können die meisten Plugins entfernt werden... dann gehts ev.  etwas schneller.
