### ISSUE TITLE
Connect on Enter

### ISSUE THREAD

**Issue by Lysemose** [rzander/sccmclictr#129]
When entering a "Target Computer", pressing enter no longer triggers a connect
![Annotation 2019-09-26 142922 - Copy](https://user-images.githubusercontent.com/1898246/65687745-29907900-e06a-11e9-9b3c-946d9504fb30.png)

**Comment by rzander** [comment]
Already fixed: https://github.com/rzander/sccmclictr/issues/125

**Comment by Lysemose** [comment]
Arhh, sorry Roger didn't see the closed issue. Perfect!
