### ISSUE TITLE
enhancement: "Override ServiceWindow" fehlt

### ISSUE THREAD

**Issue by horst789github** [rzander/sccmclictr#133]
im alten SCCM Client Center konnte man bei Advertisements Rechtsklick > "Override ServiceWindow" machen und dann "rerun advertisement" so läuft das advertisement trotz das kein service window aktiv ist... dies fehlt mir in der neuen variante.

**Comment by rzander** [comment]
Ich behaupte, das braucht es gar nicht... Wenn ReRun Advertismenet getriggert wird so wird die installation gestartet, egal ob mit oder ohne MaintenanceWindow. Im PowerShell vom ClientCenter siehst Du dass bei Trigger das deployment geändert wird und der Wert <OverrideServiceWindows>TRUE</OverrideServiceWindows> gesetzt wird....

**Comment by horst789github** [comment]
nein geht nicht:

![grafik](https://user-images.githubusercontent.com/35397597/66658885-b169ac00-ec42-11e9-902a-b31c29d67fa7.png)

**Comment by rzander** [comment]
Gemäss Log ist das ein TaskSequenz, kannst Du bitte prüfen ob die PkgID auch wirklich die richtige ist, sonst
![image](https://user-images.githubusercontent.com/11909453/66660015-bfb8c780-ec44-11e9-8c16-3a6f8d412eb3.png), dann werden alle PkgID's angezeigt...

**Comment by rzander** [comment]
[Fix.zip](https://github.com/rzander/sccmclictr/files/3718328/Fix.zip)
Zum testen, die Dateien aus dem Fix.zip ersetzen...

**Comment by horst789github** [comment]
perfekt, funktioniert !
