### ISSUE TITLE
enhancement: msinfo32 shortcut fehlt

### ISSUE THREAD

**Issue by horst789github** [rzander/sccmclictr#135]
Im alten Client Center gabs (für mich sinnvoll und oft genutzt) einen shortcut zum msinfo32... vielleicht könnte man das wieder einbauen?

**Comment by rzander** [comment]
Existiert bereits für alle Spender: https://github.com/rzander/sccmclictr/wiki/3)-Installation#plugins

**Comment by horst789github** [comment]
bin spender und sehe es nicht, wo finde ich es ?
![grafik](https://user-images.githubusercontent.com/35397597/66653100-8cbc0700-ec37-11e9-9ede-00fdfdcf0eb6.png)

**Comment by rzander** [comment]
Etwas versteckt... 
![image](https://user-images.githubusercontent.com/11909453/66655759-f25ec200-ec3c-11e9-8a52-c323d8aa29cb.png)

Der Reiter "Custom Actions" war eigentlich gedacht für Tools die nicht zwingend eine Verbindung zum Client brauchen, da diese immer gestartet werden können. MSInfo32 braucht einen laufenden Client...
