### ISSUE TITLE
Can you please include to get the BIOS Version on the next release

### ISSUE THREAD

**Issue by NarayanasamyB** [rzander/sccmclictr#139]
Can you please include to get the **BIOS Version** on the next release

**Comment by rzander** [comment]
Do you mean `(Get-WmiObject win32_BIOS).SMBIOSBIOSVersion` ?

**Comment by NarayanasamyB** [comment]
Yes Roger

Best Regards,
Narayanasamy B
________________________________

**Comment by rzander** [comment]
Implemented in https://github.com/rzander/sccmclictr/commit/ccfba1a90160940f6597cda1bc8787fc4b0bf6d5

**Comment by pilgi3** [comment]
@rzander Do you have implemented in the version 1.0.6.1 preview? I can't see the script in PSScripts.

**Comment by rzander** [comment]
It's not in PSSCripts, it's in "Adhoc Inventory":
![image](https://user-images.githubusercontent.com/11909453/73765962-9e409600-4775-11ea-9397-4b3d4c1dd008.png)

**Comment by realkazman2000** [comment]
I just save this powershell line as Model_info.ps1 and save it in the run custom powershell folder. So its from the main screen ;)

$(gwmi win32_computersystemproduct).version +" "+ (gwmi win32_computersystem).model +  " Bios: " +  $(gwmi win32_bios).smbiosBIOSVersion;

**Comment by pilgi3** [comment]
Thank you!
