### ISSUE TITLE
Function to clear the update cache

### ISSUE THREAD

**Issue by Xento** [rzander/sccmclictr#14]
I think it would be really helpful to have a button to clear the software update cache.
I implemented it quick&dirty in my version.
Maybe you could add this function to your lib and put a button in the client.

**Comment by SCCMAdmin** [comment]
Hi @Xento, do you mean the cache under %windir\SoftwareDistribution ?
If yes, that's handy although I've never felt the need to do that.

What I have needed to do on many occasions is to flush that folder entirely, as in explicitly:
net stop wuauserv
rd /s %windir\SoftwareDistribution (always C:\Windows for us)
net start wuauserv

Would be useful as a "Reset WUA" button of some sort. 
Maybe the:
- light option would be your clearing of the software update cache idea; and the 
- heavy option would be reset WUA.

Thoughts?

Thanks,

**Comment by Xento** [comment]
This is exactly what I mean ;-)

**Comment by kintaroju** [comment]
Hi Guys,

don't want to be promoting another project on someone else's discussion thread, but the sledge hammer approach i do to fix Windows Update issues is with ConfigMgr Client Health 

https://gallery.technet.microsoft.com/ConfigMgr-Client-Health-ccd00bd7

It fixes GPO, WMI, and WUA. But yea if there was a quick clean way to fix WUA issues as another feature that would be great too. 

Cheers!

**Comment by rzander** [comment]
Reset WUA and/or the Client Health script would be a great part for a Plugin as then it's easy to remove for those wo don't want that feature... Any volounteers ?

**Comment by SCCMAdmin** [comment]
@kintaroju I'll check out that link later. Sounds cool. Need to delve into it. It is still a separate thing and complements client center in my opinion.

@rzander Roger, I'm not a coder. So I can't volunteer unfortunately. However as an admin, on the positive side I'm a heavy user of your application and can certainly test it in a large environment (~15,000 endpoints). Happy to help in this regard. Per previous conversations, I'm planning to package up and deploy client center to ICT staff with associated use case documentation. Might even be able to get my company to donate per head, who knows. Before that happens, I'll promote personal donations.

**Comment by SCCMAdmin** [comment]
Hi @kintaroju @rzander @Xento.

If we have the steps scripted already, like the Reset WUA three commands I listed above. Can't we already easily execute that one script? 

I have a very old batch file i found online and edited slightly called ITMUFix as you might recall ITMU within SMS2003. It was basically doing similar whilst also fixing BITS and Windows Update services and re-registering files. I'll have to dig it out and see if SoftwareDistribution folder removal was a part of it. If you are interested, I can share the batch. Is that something I can easily attach here without being blocked out as it is a script?

**Comment by rzander** [comment]
That may be a good Point, a Plugin that does list existing PowerShell scripts... So you can create with PowerShell whatever you want. Just place the .PS1 file in Folder and you will see it in ClientCenter...

And in the near future with CM1706, you can use these scripts directly in ConfigMgr...

**Comment by rzander** [comment]
Created a Plugin that does show PowerShell scripts stored in a Folder:
![image](https://user-images.githubusercontent.com/11909453/27994494-a581c830-64bf-11e7-869c-4bbece70b5d6.png)

Please post some PowerShell scripts you want to see there !!!

**Comment by SCCMAdmin** [comment]
Awesome @rzander ! How about the script from the link above that @kintaroju pasted in? I haven't used it but it looks very interesting and something that would provide a good starting point for potentially any environment.

I'm new to PS and training on it now (to any reader, I can highly recommend Microsoft Virtual Academy learning path content). Would love to add new creations in for sure as they come. I'm happy to offer the suggestion of the framework you are creating and then it really is open to need and imagination. :-)

When you say add it to the folder, where is this scripts path?
Re customisation and deployment, can PS scripts be slipstreamed in via a transform using the ideas from your past steps documented at codeplex?
(Before codeplex goes offline entirely, do you plan to add in any of that content that only lives there to GitHub? If not, under the Documentation issue I can work to bring them over here) 

Thanks!

**Comment by kintaroju** [comment]
Hi @SCCMAdmin ,

For that script it requires some modification as it reads the configuration from an XML file that you need to specify, so you might want to visit that technet gallery link and read the person's blog. Once you get it setup the way you want it'll work like a charm. 

@rzander Awesome idea to add that powershell function, will that be a dynamic thing so you can place your own scripts or will it have to be something you have to hard code in?

Cheers!

**Comment by rzander** [comment]
Yo can place folders and scripts into the PSScripts Directory which is in the Client Center Installation directory:

![image](https://user-images.githubusercontent.com/11909453/28031658-4876eca8-65a8-11e7-8e13-06c2202f7ede.png)

**Comment by rzander** [comment]
Will release the PSScript Plugin in the next few days (V1.0.3.7)
