### ISSUE TITLE
How get PRO version?

### ISSUE THREAD

**Issue by itkroplis** [rzander/sccmclictr#140]
Hi!
I want to get PRO version. But I don't understand how it is possible.
I see info  Donate 10$ and you will get a License Key. I do PayPal? Where I get License Key? e-mail?
If yes, where that key can write?

**Comment by horst789github** [comment]
yes you only need to "donate" over paypal... i donate on 27.09.2019, 18:33 and on 27.09.2019, 19:04 the @rzander send e-mail to my paypal e-mail and send me the license key and a manual how to "install" the license.

**Comment by rzander** [comment]
It's a "manual" process to generate the Keys.. so it may take a second or two until you receive the key... If it takes more than 48h; send me a Mail or open an Issue here...
