### ISSUE TITLE
MSI console extension registration for 1910+

### ISSUE THREAD

**Issue by theaquamarine** [rzander/sccmclictr#145]
With the name change in 1910, the console is installed to `%programfiles(x86)%\Microsoft Endpoint Manager\AdminConsole` rather than a Microsoft Configuration Manager folder, and it appears the MSI's action to install the console is working on the wrong location. The "Register Console Extension" action in the menu works correctly.

`%SMS_ADMIN_UI_PATH%` is updated to point to `C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin\i386`

**Comment by rzander** [comment]
Installed ClientCenter on a fresh  TP2001 and the Console Extension was installed automatically... The target directory is defined from HKLM:\SOFTWARE\Wow6432Node\Microsoft\ConfigMgr10\Setup , "UI Installation Directory". MSI Custom Action is using `SCCMCliCtrWPF.exe /RegisterConsole` which is the same code as if you register console extension from within the tool...
I cannot reproduce this Issue.

**Comment by theaquamarine** [comment]
Yeah, I'm not sure what went wrong there, but I've not been able to reproduce the issue either, sorry. Thanks for looking in to it!
