### ISSUE TITLE
Search in "Installed Software"

### ISSUE THREAD

**Issue by pilgi3** [rzander/sccmclictr#146]
Is it possible to provide a search for the "Installed Software"?
Sometimes there are devices with so much entries.
Or it is possible to press a key, e.g. "t" to jump to like in the windows explorer?

![image](https://user-images.githubusercontent.com/44865075/72725547-5242fe00-3b86-11ea-9af0-b3fc827bc2b6.png)

**Comment by SCCMAdmin** [comment]
Pressing a key to jump to a letter would be excellent. No real need for search after that. One letter versus typing in a one word or name. :-]

**Comment by rzander** [comment]
Implemented in https://github.com/rzander/sccmclictr/commit/50a89ee5282c3db7bc5727d666f10bc840e8ddcb
Only first pressed character is used to jump.
