### ISSUE TITLE
Offline installer ?

### ISSUE THREAD

**Issue by barbuslex** [rzander/sccmclictr#15]
Hi,

Is it possible to get an offline installer ? Because my admin computer is not connected to internet.

Thanks in advance

**Comment by rzander** [comment]
Download the Release from here: https://github.com/rzander/sccmclictr/releases ... 
If you are offline, remove the file "Plugin_SelfUpdate.dll" and "Plugin_RuckZuck.dll"  (after the Installation) as these require Internet Access...

**Comment by rzander** [comment]
Readme was updated with a "Downloads" section...

**Comment by barbuslex** [comment]
Thanks
