### ISSUE TITLE
admin install with 1.0.6.1

### ISSUE THREAD

**Issue by chrisduda** [rzander/sccmclictr#150]
Am trying to install the latest .msi version and am getting an error stating "client center for configuration manager requires installation by an admin user account".  Am a local admin on my computer, version 1.0.5.5 installs without issue.  Any ideas?

**Comment by horst789github** [comment]
try rightclick > run as administrator 
or
open cmd as admin and run the .msi from the admin cmd

cause is maybe the UAC ( User Account Control GPO )

**Comment by chrisduda** [comment]
MSI doesn't have the option to run as administrator, only .exe's.  However, running the msi through an elevated command prompt worked fine.  Thanks for the tip.
