### ISSUE TITLE
[Enhancement] Show FreeSpace/DiskSpace not in Bytes

### ISSUE THREAD

**Issue by horst789github** [rzander/sccmclictr#151]
Hi Roger,

please change in "inventory data" the "Adhoc Inventory" freespace/diskspace bytes in MB/GB the bytes 

Example:
FreeSpace: 5,02 GB

THX

**Comment by rzander** [comment]
That's not that easy as it sounds... All the AdhocInventory action are WMI queries (check out sccmclictrwpf.exe.conf). I don't think you can convert the result in WMI ?!
Why not using the "Get\Free Disk Space.ps1" PowerShell script -> ` (([wmi]"root\cimv2:Win32_logicalDisk.DeviceID='C:'").FreeSpace/1GB).ToString("N2")+"GB"`

**Comment by horst789github** [comment]
maybe you can use on this function a powershell function?
![grafik](https://user-images.githubusercontent.com/35397597/74967711-d3a5de80-5419-11ea-9bd6-43c3927e0551.png)

**Comment by rzander** [comment]
Adhoc queries are WMI based. But you have a "Run PS" button where you have the corresponding PowerShell in the Drop-Down List:
![image](https://user-images.githubusercontent.com/11909453/74968157-a443a180-541a-11ea-8e5e-c5adf021cc20.png)

**Comment by horst789github** [comment]
thx for the workaround, but this is now a "longer way" as in old version. In the old SCCM Client Center i see very fast the free space in "Agent Actions" > Cache > Get list" (in bottom i see "Free Space on Drive: 8000 MB"
 any chance to get it back?
