### ISSUE TITLE
Button "Application related actions" does nothing

### ISSUE THREAD

**Issue by pilgi3** [rzander/sccmclictr#152]
There is no default action when i click on the button
![image](https://user-images.githubusercontent.com/44865075/74912346-d6bfb100-53be-11ea-85a1-2c4421c819b6.png)

Machine Policy (and User Policy) has a default action
![image](https://user-images.githubusercontent.com/44865075/74912515-29996880-53bf-11ea-9fc1-63ef2733e706.png)

Is it possible to define a default action or maybe all three get kicked off?

**Comment by rzander** [comment]
Makes sense.. I'm mostly using the ".. gobal evaluation action". I'm not sure of the other two do something ;-)

**Comment by SCCMAdmin** [comment]
Like Maintenance, App Mgmt is a drop down menu and you select what you want to do next @pilgi3 .

I would vote to leave it as is or to default to Global Evaluation Action.

**Comment by pilgi3** [comment]
I think i could be helpful to define a default action. Maybe the best is "Application manager global evaluation action". When i want trigger actions on a device i click on the Top Button not on every entry in the dropdown menu.

**Comment by pilgi3** [comment]
@rzander do you think about to add this in future release?

**Comment by rzander** [comment]
Implemented: https://github.com/rzander/sccmclictr/commit/22b20bc6c961cd089737a2c70253dd0c76725faf
