### ISSUE TITLE
Client Center behind a Firewall

### ISSUE THREAD

**Issue by dpuls** [rzander/sccmclictr#159]
Dear Community,
My SCCM with Client Center runs behind a Firewall.
IT is correct that only the WinRM default HTTP port 5985 and the default HTTPS port is 5986 is neccesary for connect to clients? What about ports in redirection from client to SCCM?

Thanks

**Comment by rzander** [comment]
Yes ClientCenter is using PowerShell remoting which requires WinRM (5985) to connect a client. 
If you can connect a remote device with `Enter-PSSession {HOSTNAME}` then ClientCenter should also be able to connect...
If you want to open the "Logs" or "ccmcache" directory, you also need to open ports to access FileShares...
