### ISSUE TITLE
Download location when not using Windows 10

### ISSUE THREAD

**Issue by SCCMAdmin** [rzander/sccmclictr#16]
Hi All,

Not all of our IT staff are using Windows 10 yet, (we've got a mix of all OS, Win7 is the oldest thankfully). This means they don't have Windows Store access. Also, globally in our enterprise we are about to disable the Windows Store for customers (all users including ICT).

So the question is, where does one download sccmclictr from? 

I've searched high and low here in GitHub and I can't find an actual download link for an installer / zip etc. Yes I can see code and individual files. As a GitHub newbie, maybe someone can point me and future readers of this point in the right direction.

Once answered, I will add this to the documentation chat (#9) and Wiki chat.

Thank you.

**Comment by rzander** [comment]
I've updated the readme with a section for the downloads...
