### ISSUE TITLE
license request

### ISSUE THREAD

**Issue by psyki94** [rzander/sccmclictr#160]
Hi,
I'm addict to your product :)
I made a donation to recover the license.
But did I get nothing?
How can I recover the license please?
Thanks for your feedback.

**Comment by horst789github** [comment]
if you already had a license, you should find it in your email inbox.

**Comment by psyki94** [comment]
Thank you for your reply but I did not receive anything ... :(

**Comment by horst789github** [comment]
the body contains the following message in the e-mail:

> Many thanks for your kind donation to the Client Center for Configuration Manager Project.
> 
> As promised, you can use the following license data to get rid of the license screen and to activate some other goodies
> 
> Licensee: 
> License Key:

otherwise just wait until roger answers.

**Comment by psyki94** [comment]
ok, it's weird ... i still have nothing.
not in my inbox, not in spam.
I'll wait for roger's response. Maybe he has to validate the payment?
So excited to have the full product!

**Comment by horst789github** [comment]
basically, this is not an automated process, but roger sends it by hand.

**Comment by rzander** [comment]
It's a manual process to create the key... and therefore it may take a moment :-)

**Comment by psyki94** [comment]
everything is OK !
I have received the license key.
Thank you very much Roger.
I will be able to manage my clients perfectly !!!
