### ISSUE TITLE
Store for Business version still on 1.0.5.5?

### ISSUE THREAD

**Issue by Ginolard** [rzander/sccmclictr#161]
Hi,

The Microsoft Store version is still on 1.0.5.5 even though it says that the build is based on [this release](https://github.com/rzander/sccmclictr/commit/5d74fbe7d99a1df437c08ad3627a548e8f74f436) which seems to point to the latest one?

Can you update the MIcrosoft Store version?

**Comment by rzander** [comment]
It's on the way... I hope it will pass the certification process this time without any issues ....

**Comment by rzander** [comment]
Certificate is done (this time, it was super-fast)... Do you have received the updated Version 1.0.7 ?

**Comment by Ginolard** [comment]
Yup! Great support, thanks!
