### ISSUE TITLE
Weird behavior when connect with "Enter" instead click on "Connect"

### ISSUE THREAD

**Issue by pilgi3** [rzander/sccmclictr#165]
I type in the name of the device and press "Enter".
After this I get the message "Unable to connect".
So i press "Enter" to close the message and the message comes up again?
Only click "OK" with the mouse stops the loop.

When I connect with the "connect" button I can press "Enter" to close the "unable to connect" message.
It seems the problem is only when press "Enter" to connect.

**Comment by rzander** [comment]
I cannot reproduce this bahavior... Which Version are you using? MSI or ClickToRun or MSIX/Store source ?

**Comment by pilgi3** [comment]
I tried on a second client - same behavior. 
Both are version 1.0.6.1 installed with MSI.

**Comment by rzander** [comment]
Sorry, I have used a client which was available..
Can reproduce the Problem now.

**Comment by pilgi3** [comment]
Any news when this behavior will be fixed?

**Comment by pilgi3** [comment]
@rzander Do you know when this issue get fixed?

**Comment by pilgi3** [comment]
@rzander Any news about the fix?

**Comment by SCCMAdmin** [comment]
Yes I know this behaviour, a little annoying. To get out of the error connecting dialog, I usually click the window X or Esc on k/b. If you hit enter it will attempt to connect again and be stuck in a loop.

**Comment by pilgi3** [comment]
@rzander Any news when version 1.0.7. will be available. The Problem still exist, and other issues I have reported where implemented in 1.0.7.

**Comment by pilgi3** [comment]
I have tested the behavior on version (pre release) 1.0.7.1 and unfortunately the issue still exist.
@rzander do you have any idea how to fix this?

**Comment by pilgi3** [comment]
Any chance to get this fixed soon?

**Comment by pilgi3** [comment]
The issue still exist a very long time. will this be ever fixed?

**Comment by Xento** [comment]
I think this will fix it https://github.com/rzander/sccmclictr/pull/197
It occours because the textbox listens for keyup. So when you dismiss the error message with enter, it will be dismissed on keydown and the keyup event is than catched again by the textbox.

**Comment by pilgi3** [comment]
Yes, with version 1.7.2 it is fixed now!
Thank you so much!
