### ISSUE TITLE
Offline installer cabinet has an invalid digital signature

### ISSUE THREAD

**Issue by barbuslex** [rzander/sccmclictr#17]
Hi,

When i try to install offline installer i have this error ; 

![image](https://user-images.githubusercontent.com/113057/27677355-a135f906-5cb1-11e7-8b32-ca4a523cfb87.png)

Have you an idea to solve it ?

Thanks

**Comment by rzander** [comment]
as from http://sccmclictr.codeplex.com/workitem/1702 , your Computer does not fully trust the signature. Make sure you have updated your root certificates and if you do CRL checking, your Client must be able to check the CRL for the signature (Internet Access required)

**Comment by barbuslex** [comment]
The computer where Client Center will be installed does not have internet connection...
How can i update root certificates without internet ?

**Comment by rzander** [comment]
Configure Trusted Roots and Disallowed Certificates: https://technet.microsoft.com/en-us/library/dn265983.aspx

**Comment by barbuslex** [comment]
Thanks for your help.
I have follow this tutorial  : https://www.arnavsharma.net/windows-server/updating-ctls-in-disconnected-environments-in-windows
It works perfectly now !
