### ISSUE TITLE
Unable to connect using IP Address

### ISSUE THREAD

**Issue by NarayanasamyB** [rzander/sccmclictr#170]
Hi Mate,

I was trying to connect the systems using the IP Address, but i counldn't connect. even i have tried to manually put the User Name and Password but still unable to connect.

**Comment by rzander** [comment]
That's the default behavior for WinRM. You have to configure TrustedHosts in WinRM to allow connections with an IP.
https://docs.microsoft.com/en-us/windows/win32/winrm/installation-and-configuration-for-windows-remote-management

You can test with PowerShell by using:
```PowerShell
Enter-PSSession <target IP-Address>
```
