### ISSUE TITLE
Get OS Version PS script shows "wrong" OS version

### ISSUE THREAD

**Issue by pilgi3** [rzander/sccmclictr#173]
If I use the script on a 20h2 device I got this output
![image](https://user-images.githubusercontent.com/44865075/113979588-b7dfe080-9845-11eb-8c6b-fff0949ca679.png)

I know you read the info from the registry but Microsoft uses the Display Version instead of ReleaseId.
![image](https://user-images.githubusercontent.com/44865075/113979956-363c8280-9846-11eb-8f9b-fdf44cf345ac.png)

![image](https://user-images.githubusercontent.com/44865075/113979753-f37aaa80-9845-11eb-95fa-370d5764acb2.png)

So may you could change the script please?
Thanks!

**Comment by rzander** [comment]
Fixed in https://github.com/rzander/sccmclictr/commit/9ead4854dcd17a385dfb247d6c157af14260328b

**Comment by davisdre** [comment]
Glad to see this addition. I haven't downloaded the pre-release of 1.0.7.x, but I can confirm that script does work.
