### ISSUE TITLE
Shortcut to execmgr.log / smsts.log

### ISSUE THREAD

**Issue by pilgi3** [rzander/sccmclictr#177]
In the application section there are already buttons to open three logfiles.
![image](https://user-images.githubusercontent.com/44865075/117410635-fd5dff00-af12-11eb-9b28-fffdf5e6fa62.png)

It would be great if you could do the same in "Advertisements" for the "execmgr.log" and "smsts.log"
![image](https://user-images.githubusercontent.com/44865075/117411003-647bb380-af13-11eb-8983-f28dff4c0421.png)

Thanks!

**Comment by pilgi3** [comment]
Any chance to become this implemented?

**Comment by rzander** [comment]
Implemented: https://github.com/rzander/sccmclictr/commit/d191bc1e15adaa1461f48439b02c776b92443bad
