### ISSUE TITLE
Can we have the Option or ability to Lock the System

### ISSUE THREAD

**Issue by NarayanasamyB** [rzander/sccmclictr#182]
The reason is, if the system got disconnected while in the middle of remote session and if nobody there physically to accept the connection back then its difficult to take the remote and only option is to logoff and the reconnect through CMRC

![image](https://user-images.githubusercontent.com/39905917/137016757-8856209f-ad34-4300-9f50-8ff22c94962a.png)

**Comment by rzander** [comment]
Can you provide a powershell command to lock a remote device.... ?!

**Comment by NarayanasamyB** [comment]
Yes, its working, will you be able to bring that on the client center itself(Ex: like above) ?
