### ISSUE TITLE
Client Centre crashes on Windows Sever 2019 

### ISSUE THREAD

**Issue by RobertLintner** [rzander/sccmclictr#187]
Can you please confirm if the Client centre can be used on the server 2019. Initially when it gets install it works but once the server is rebooted the Client centre opens and then it stops responding.

**Comment by RobertLintner** [comment]
We are using the free version at the moment. If we were to pay would that help? Would we get a support? The free version was working fine on our old 2016 servers.

**Comment by rzander** [comment]
I have customers running the tool on server 2019... For troubleshooting, remove all plugin*.dll in the directory of the executable... Specially the "Plugin_SelfUpdate.dll" has problems if there is no internet connection...
> Note: Donating is like spending a beer as it does not grant you any additional rights...
