### ISSUE TITLE
Request - Clispy integration if possible?

### ISSUE THREAD

**Issue by kintaroju** [rzander/sccmclictr#19]
Hi @rzander ,

Back in the hay day, you wrote the earlier version of the client center for SCCM for 2007, and one tool that was awesome in there was the clispy integration you had, do you have any plans to bring that back again to this version of client center for SCCM? I've got a screenshot of your old client center interface below that I'm referring to :D 

![image](https://user-images.githubusercontent.com/29717036/27746477-35ec9ba2-5d7c-11e7-8a4e-10457c321556.png)

Cheers!

**Comment by rzander** [comment]
Running Executions is for Packages onyl. If you really need the status of running packes just go to:
![image](https://user-images.githubusercontent.com/11909453/27747677-777667f6-5dcc-11e7-8ca0-6ff23a6928fb.png)

**Comment by kintaroju** [comment]
Hi @rzander,

Awesome, it's like a hidden gem in your app :D , thanks for the great info :D.

I'll make the time to indicate that on the Wiki.

Cheers!
