### ISSUE TITLE
Unable to launch when running as elevated admin account

### ISSUE THREAD

**Issue by TobyBCC** [rzander/sccmclictr#198]
When I run the application as my elevated access account the application starts and is visible on the screen but the loading wheel just continuously spins and doesn't timeout. When I run the application as my standard account it works fine, however I am then unable to connect to 'localhost' and need to put in the name of my computer and my elevated account credentials in the credentials location to connect.

Are there any logs I can access to see what might be causing the issue?

I have donated and have the premium version of the application. Thanks, other than this issue it's an amazing application and has saved so much time for me.

I am on v1.0.7.2 assembly 1.0.7.26543.

**Comment by rzander** [comment]
Does it help if you delete Plugin_SelfUpdate.dll ?! ... I've seen similar issues which where related to this plugin...
