### ISSUE TITLE
RemoteRegistry Service Start and Stop

### ISSUE THREAD

**Issue by KuLeh** [rzander/sccmclictr#2]
Is it possible to install a task in the ClientCenter so that you can temporarily set the "RemoteRegistry" service to "Manual" and then start it?
Then a task to "stop" and "disabled" the service again.

**Comment by rzander** [comment]
Agree, will be part of V1.0.3.5...

**Comment by rzander** [comment]
Implemented

**Comment by KuLeh** [comment]
Thanks for the quick implementation.
I'll try it then...
