### ISSUE TITLE
Pending Updates Deadline Appears Incorrectly in 1.0.3.6

### ISSUE THREAD

**Issue by SCCMAdmin** [rzander/sccmclictr#20]
Hi @rzander :-) Hope you are good.

Here is something I touched on in e-mail but I was using v1.0.1.0 back then so I upgraded to 1.0.3.6 running on Win7 x64. I can confirm the issue is still present and the issue is:

There are outstanding software updates on the remote PC after the deadline has passed. You connect, go and click on Inventory > Pending Updates. The pending updates are shown and the deadline column is showing the incorrect date and time. It appears to be forward offset by the remote PC time zone.

e.g. deadline is 7/13/2017 20:00 local client time (US dates due to our US based Primary site).
deadline in sccmclictr shows as 7/14/2017 06:00. This is 10hrs ahead of when it actually is and exactly matches the PC time zone being GMT +10.  I think the +10 is being added on and not accounted for correctly in sccmclictr.

It happens to be 7/14/2017 12:47 as I submit this, however connected to at the right time as a different admin scenario, the deadline can appear into the future when it actually has already passed.

Let me know what you discover. Thank you.

**Comment by rzander** [comment]
If you have missing Updates, can you please run the following Command to List the Deadlines:
`get-wmiobject -query "SELECT * FROM CCM_SoftwareUpdate" -namespace "ROOT\ccm\ClientSDK" | select-object Name, Deadline | fl *`

You will get a List of Updates with Deadline like:
`Deadline : 20170714100700.000000+000`

The Time is always UTC (+000 means no time shift), so the System does calculate the Time based on the TimeZone of the Host running ClientCenter... That should be the time you get in ClientCenter.

I have the Impression that there is something wrong with the Deadline that is comming from WMI (CCM_SoftwareBase) as it has always the UTC Format but the time-shift is already added. 

So I can subtract the TimeShift to get the right time, but on the other side that's something that Microsoft should fix, as the Deadline seems to have the wrong Format...

I will check if I can correct that without raising any other issues...

**Comment by rzander** [comment]
I think I could fix it with V1.0.3.7 ...

**Comment by SCCMAdmin** [comment]
I will get back to you on this one once I've had a chance to test this command when I'm back at work and we let the July updates free. Thanks for the test idea.

I don't think the time is always UTC. It depends how you choose to deploy in the deployment properties like selecting client local time. I guess it could still use UTC then add local client offset then it equals client local time. All that is remote client... then the host running ClientCenter adds its local client offset again, here is the issue.

**Comment by SCCMAdmin** [comment]
Confirmed resolved in 1.0.3.7. Thanks Roger! @rzander 

FYI the command:
get-wmiobject -query "SELECT * FROM CCM_SoftwareUpdate" -namespace "ROOT\ccm\ClientSDK" | select-object Name, Deadline | fl *
...produces:
Name     : Windows Malicious Software Removal Tool - July 2017 (KB890830)
Deadline : 20170727170000.000000+000

This is actually the local client time deadline from deployment:
![image](https://user-images.githubusercontent.com/29601648/28418559-7c239d18-6d9f-11e7-8b47-95edd825e16e.png)

It's a GMT+10 or UTC+10 timezone on that remote client PC (same as admin PC running client center) even though the SCCM server setting the deployment as shown is GMT-5. :-)
