### ISSUE TITLE
locking on startup

### ISSUE THREAD

**Issue by nordic-paul** [rzander/sccmclictr#201]
Current Version: 1.0.7.2
Assembly Version: 1.0.7.26543

Starting the app a second or third time, the Target Computer is pre-populated with the previously connected computer
The app refuses to respond to any mouse clicks and must be killed with Task Manager

If I delete the folder in
C:\Users\username\AppData\Local\Zander_-_Tools

I can start the app and everything works again

**Comment by rzander** [comment]
Try to delete the "Plugin_SelfUpdate.dll" as it seems this generates some issues...

**Comment by nordic-paul** [comment]
Seems to have done the trick! Thanks :)
