### ISSUE TITLE
FIX-WindowsUpdate.ps1 - security risk, adds asterisk to the TrustedHosts list

### ISSUE THREAD

**Issue by EckeD** [rzander/sccmclictr#204]
in the "FIX-WindowsUpdate.ps1" script, in line 119 the TrustedHosts list is set to * - which would allow any device to connect:
`Set-Item -Path WSMan:\localhost\Client\TrustedHosts -Value '*' -force`
I would **strongly** suggest to remove or at least comment this line out from the script, as it poses a security risk and also is unnecessary.
If the list needs to be fixed, the admin of the environment should do that appropriately, outside of this script.

**Comment by rzander** [comment]
It's now commented out...

**Comment by MN-EckeD** [comment]
thanks! :)
