### ISSUE TITLE
Invalid Digital Signature

### ISSUE THREAD

**Issue by Miraj943** [rzander/sccmclictr#21]
Good morning,

I am trying to install the latest Client Center but I am getting the following:

A file that is required cannot be installed because the cabinet file ... has an invalid digital signature. This may indicate that the cabinet file is corrupt. 

I noticed that the cert on the file is dated July 14, 2017. Can it be updated so I can install it on my machine please?

Thanks,
Michele

**Comment by rzander** [comment]
check out  Issue https://github.com/rzander/sccmclictr/issues/17 ...

**Comment by rzander** [comment]
Close that...
