### ISSUE TITLE
1.0.7.2 after connect not clickable

### ISSUE THREAD

**Issue by kasparssc** [rzander/sccmclictr#210]
Hi.Thanks for great tool. 
After connection is done to remote computer nothing is clickable in tool.
Can kill only in taskbar by closing window.
Does anyone run into this kind of behaviour?
Tool worked month ago. Only Win10 updates were installed.

**Comment by rzander** [comment]
This sound like the Issue with the SelfUpdate plugin... Find and delete "Plugin_SelfUpdate.dll" and retry...

**Comment by kasparssc** [comment]
Thanks. I renamed dll file and now it works again.

**Comment by kasparssc** [comment]
Thanks
