### ISSUE TITLE
`Enable-TSDuplicateToken`

### ISSUE THREAD

**Issue by ghost** [rzander/sccmclictr#213]
What is the purpose of having this function in the executable? It was recently flagged by our InfoSec department.

**Comment by rzander** [comment]
The tool is Open-Source, feel free to check the code...  It's to decode Secrets like Variables -> https://rzander.azurewebsites.net/network-access-accounts-are-evil/

**Comment by ghost** [comment]
@rzander thanks for the response. I did check the code and I found the references in 3 files but I am not overly familiar with C# so I wasn't able to decode how it was being used. 

I was able to look at the git blame and show our InfoSec that you added this 11 years ago. The use case makes sense, thanks again!
