### ISSUE TITLE
Runing GPUpdate via"run PS" do not show completion meassage. 

### ISSUE THREAD

**Issue by ketonic** [rzander/sccmclictr#23]
Using the new Powershell script function we wanted have a easy way to force a gpupdate on the client PC and that is working just fine, the issue we are having is that we do not get any feedback in the "console" after the "Updating Policy...", we would like to also see the two "completed successfully" outputs.

**Comment by ketonic** [comment]
Should this have been a request or is it actually a bug?

**Comment by rzander** [comment]
It's by design ... it expects a single string as return value and not multiple lines... 
or try:
`(gpupdate) -join ""`

a bit ugly bit it works :-)
