### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ogeccut** [rzander/sccmclictr#24]
WinRM is configured.
PS version 5.1
.NET version 4 installed

What else could be an issue?
Thank you.

**Comment by SCCMAdmin** [comment]
Hi @ogeccut 
Please see the Wiki tab, section 2 and scroll to bottom WinRM Troubleshooting and give that a go.
Thanks

**Comment by ogeccut** [comment]
there are only 2 lines for WinRM
Authentication for Remote Connections (WinRM)
Unable to Connect WinRM because authentication packets are over 16k
And one for sccm compliance, 

I am just trying to connect to a local host.
WinRM service is already running on this machine.
WinRM is already set up for remote management on this computer.

**Comment by rzander** [comment]
Have you tried to connect a remote Computer by using PowerShell directly:
`Enter-PSSession computername`
Are you able to connect or do you get an error ?

**Comment by SCCMAdmin** [comment]
@ogeccut  I also find when connecting to localhost you firstly need to run as admin when the clientcenter tool is opened. I then always use the hostname and administrative credentials (i.e. don't use localhost and don't leave credentials empty). Let us know which way you solved it so we can ensure we document for future readers.

Post your error from status box (or otherwise) too to give us some visibility. Thanks. :-)

**Comment by kintaroju** [comment]
@ogeccut one long shot is I noticed that WinRM will have issues with multiple NICs especially with VMware based NICs as there are sometimes multiple firewall profiles which prevent the usual cocktail of WinRM commands to work.

**Comment by ogeccut** [comment]
using hostname as target computer. Added local admin fro credentials....Still unable to connect.
I do have local VMwarkstation installed.

**Comment by kintaroju** [comment]
Try this script, if the system you are connecting to has vmware:

https://gist.github.com/gschizas/4958672

Then after running script try enabling winRM, also try to check the error output when enabling winRM

**Comment by rzander** [comment]
Are you able to connect with PowerShell ?
No = we can close the Issue as it's a PowerShell/WinRM thing...
yes = we will see...

**Comment by ogeccut** [comment]
same error. Access is denied. 
WinRM is already set up to receive requests on this computer.
WinRM is already set up for remote management on this computer.
I ran the script. And reset VM Ethernet Adapter

**Comment by rzander** [comment]
Closed, as it's not a Client Center Issue.
