### ISSUE TITLE
Applications view InstallTime is incorrectly offset by UTC offset

### ISSUE THREAD

**Issue by SCCMAdmin** [rzander/sccmclictr#25]
Hi @rzander 

Similar to Issue #20 with deadline being incorrect by offset, I've found another one. Using v1.0.3.7, under Software Distribution > Applications view. The table showing column InstallTime. The InstallTime value is incorrectly offset by my GMT+10 time zone.

Table example:
![image](https://user-images.githubusercontent.com/29601648/28858415-a3b5c902-7793-11e7-9550-9f8cf356afe0.png)

From AppEnforce.log:
![image](https://user-images.githubusercontent.com/29601648/28858422-b7df64f6-7793-11e7-98b8-3ab8fe307096.png)

Client PC and Admin PC both GMT+10. If the +10 was not added, the correct time would be shown.

I will leave it with you to review and action. Thanks as always.

PS. at time of writing it is not the 3rd of Aug yet.

**Comment by rzander** [comment]
I still think it's a configmgr issue... but I will fix it for ClientCenter...

**Comment by rzander** [comment]
Fixed in V1.0.3.8

**Comment by SCCMAdmin** [comment]
Thanks @rzander. Legendary effort! Downloaded new one today.
