### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by tred44** [rzander/sccmclictr#26]
Have been a long time user of SCCM Client Centre on Win7. Just moved my system to Win10 and trying to setup my environment and am having an issue installing Client.Center.for.Configuration.Manager_v1.0.3.7.exe

When running the offline installer I get a 'Do you want to run this file' security warning and then on confirmation it just bombs out and nothing happens?

I've checked all the pre-requisites are installed.

**Comment by rzander** [comment]
Just installed it... Is the file signed? any security restrictions that block the execution ? You can start the .exe with paremeter "extract:<Directory>" to extract the msi files...

**Comment by tred44** [comment]
Many thanks. MSI was restricted to Bootstrapper but managed to install through logging in as local admin account (even though my domain account is administrator on PC???)
Great product, glad I've got access to it again :-)
