### ISSUE TITLE
Suggestion -- Open win10 update log 

### ISSUE THREAD

**Issue by russr123** [rzander/sccmclictr#29]
this is the cmd to do it...

Get-WindowsUpdateLog -LogPath "C:\Windows\WindowsUpdate.log" -SymbolServer .sympath  | notepad C:\Windows\WindowsUpdate.log

**Comment by rzander** [comment]
Thx, will add it as PowerShell file in the PSScript plugin (without opening Notepad as it's running on the remote Client).

**Comment by SCCMAdmin** [comment]
Why not pipe it out to cmtrace.exe so it can be properly viewed and searched with the normal toolset we are using? Notepad is rather bottom rung if you know what I mean.

**Comment by rzander** [comment]
but i assume you want cmtrace on your host and not on the target Computer... that's not possible with the PSScript Plugin as all the commands are running on the target Computer...

**Comment by bruckect** [comment]
Could you just add a button on the updates screen that links to the UpdatesDeployment.log just like you do for the WindowsUpdate.log? I find that to be just more helpful for Win10/Server2016 troubleshooting.

**Comment by rzander** [comment]
I Agree; WindowsUpdate.log does not make sense anymore on Win10/SRV16...  But it will not be part of V1.0.3.9 ...

**Comment by Xento** [comment]
Does generating the windows updatelog work on your computers?
I tried many things but i always got "unknown symbols" in the generated log.

**Comment by SCCMAdmin** [comment]
@Xento it has worked for me in the past the once I've done it in a corporate environment. Normally Win10 works so less troubleshooting going on like for Win7/8.x. Are the symbols installed? Note the command above from @russr123 (which I have not verified at time of typing this). I can test again if you need me too. When you test again, what Win10 build do you have (for comparison)?

**Comment by SCCMAdmin** [comment]
@rzander yes you are correct. cmtrace on the admin local PC, not the target PC.
@Xento a mini update for you... on Win10 1511, I ran the command line above. A log was created. Launched it and it has repeated entries looking like this:

1601/01/01 11:00:00.0000000 1352  13044                 Unknown( 35): GUID=31ca3cef-8afe-c510-1cb4-36acd097dd79 (No Format Information found).
1601/01/01 11:00:00.0000000 1352  13044                 Unknown( 10): GUID=31ca3cef-8afe-c510-1cb4-36acd097dd79 (No Format Information found).
1601/01/01 11:00:00.0000000 1352  13044                 Unknown( 10): GUID=fceb5510-7e12-b0a1-8d1b-e6a079483552 (No Format Information found).
1601/01/01 11:00:00.0000000 1352  13044                 Unknown( 10): GUID=fceb5510-7e12-b0a1-8d1b-e6a079483552 (No Format Information found).
1601/01/01 11:00:00.0000000 1352  13044                 Unknown( 27): GUID=63557808-a162-9d44-2947-0ee68c9231e2 (No Format Information found).

Is this what you are referring to? (So yeah, mine is dud too, single PC experience)

**Comment by Xento** [comment]
For some computers it works, other not.
Mine works and is 1607 an other is 1703 and doesn't work.
Yes this is exactly what I get.

**Comment by kintaroju** [comment]
Question for you guys, since there hasn't been any new traction on this, what tool do you use now to read WindowsUpdate logs since they are now ETL files?

I found a tool from Microsoft to read them which is Microsoft Message Analyzer, but the only thing I don't like about it is it doesn't do real time logging like back in the day with cmtrace. If there is a way to view the information real time I'm all ears.

**Comment by kintaroju** [comment]
Hi,

One other issue with the original suggested command is that Sybmol Packages aren't being published anymore by microsoft:

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-symbols

Is there another way to do it for systems not connected to the internet to view their logs real time?

**Comment by SCCMAdmin** [comment]
@kintaroju sorry i can't answer your Qs directly.
Using ClientCenter, I click on "run PS > Generate_WindowsUpdate.log" and the file is created. I use CMTrace to view it. Yes it is a point in time and not live.
Honestly, I rarely look into these now. I only use SCCM logs:
* UpdatesDeployment.log (downloading, installing)
* WUAHandler.log. (scanning, applying, post restart status)
Others here mentioned UpdatesHandler.log but I have never used it.

**Comment by rzander** [comment]
In V1.0.5.0 , there will be a button to open UpdatesDeployment.log and WUAHandler.log
