### ISSUE TITLE
WinRM Remote Configuration Button. 

### ISSUE THREAD

**Issue by XxQuaDxX** [rzander/sccmclictr#3]
I would like to request a new feature where you are able to activate WinRM remotely (the winrm quickconfig). I currently do this manually by running the following code on my local powershell window. It is a single line of code that turns WinRM on to the computer name given as long as you have rights to do so. It requires the PC name variable or IP of the remote machine. Once this has run you should be able to connect Client Center to the PC without needing to login or use PSExec to run the code. Start-Sleep is what I use because if there is no delay between the first and second command the second command will fail. I wasn't able to find an easier way to do this than the code below and keep it in a single line of code. An extra few seconds at the end to wait for the final command to finish is also needed before you click the connect button. 

Invoke-WmiMethod -ComputerName **PCNAME** -Namespace root\cimv2 -Class Win32_Process -Name Create -ArgumentList '"C:\windows\system32\cmd.exe" "/c winrm quickconfig -q -force"';Start-Sleep 20;Invoke-WmiMethod -ComputerName **PCNAME** -Namespace root\cimv2 -Class Win32_Process -Name Create -ArgumentList '"C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" "Register-PSSessionConfiguration -Name Microsoft.PowerShell -Force"'

**Comment by rzander** [comment]
A first Beta.. to test, extract the DLL to the ClientCenter Directory (e.g. C:\Program Files\Client Center for Configuration Manager)
[Plugin_EnablePSRemoting.zip](https://github.com/rzander/sccmclictr/files/1075685/Plugin_EnablePSRemoting.zip)

You will get the Command here:
![winrm](https://user-images.githubusercontent.com/11909453/27150649-520b8cb6-5148-11e7-9d3a-a36f7b3c3700.png)

It will trigger a "Enable-PSRemoting -force" on the remote Computer.

**Comment by rzander** [comment]
Source is available here: https://github.com/rzander/sccmclictr/tree/master/Plugins/Plugin_EnablePSRemoting

**Comment by kb0ykg** [comment]
C:\Program Files\Zander Tools\Client Center for Configuration Manager
Is that the correct location, 

I don't have (e.g. C:\Program Files\Client Center for Configuration Manager)

**Comment by XxQuaDxX** [comment]
I have the same location as kb0ykg on my PC, I placed the dll in the location I had instead. Also this seems to be working. I've tried to use it on Windows 7x64/x32 with PowerShell 4.0 and 5.0 and they all seem to work! Excellent! It does take about 20 seconds to two minutes for the PC to finish its process (Depending on the remote PC of course). Once it does you can press connect and it will connect!

**Comment by rzander** [comment]
You have to place the .dll in the same directory as the .exe is located ...  If it takes up to two minutes to einable WinRM, it may make sense to run the task in the background and show a message when it's finished...

**Comment by rzander** [comment]
Updated Version that runs the task in background...
[Plugin_EnablePSRemoting.zip](https://github.com/rzander/sccmclictr/files/1078464/Plugin_EnablePSRemoting.zip)

**Comment by XxQuaDxX** [comment]
I tried the new version on four computers so far and it worked great on three of the four. On one of them it took an extra few seconds of waiting after the message appeared for me to be able to connect (The Unable to connect message was give when I tried the first time). Overall it was much quicker than I've seen when I do it manually even. Would it be possible to have the 'Enable WinRM' button auto connect to the remote machine after it executes the powershell code? That way if it doesn't connect right away it can maybe keep trying for 20-30 seconds? The message wouldn't really be needed at that point and would avoid the need to have us manually click connect.

**Comment by rzander** [comment]
An auto connect is not possible as the "enable WinRM" button is not part of the Client Center tool, it's an external plugin...

**Comment by rzander** [comment]
released in V1.0.3.5

**Comment by rzander** [comment]
released in V1.0.3.5
