### ISSUE TITLE
msxml4

### ISSUE THREAD

**Issue by GeoffP1501** [rzander/sccmclictr#30]
I think you should remove reregistering 
msxml4.dll
msxml4a.dll
msxml4r.dll
since they show up with various vulnerability scan engines as unsupported.

**Comment by rzander** [comment]
Makes sense... msxml3x.dll seems also obsolete ?!

**Comment by GeoffP1501** [comment]
Nope, it’s still current.

Geoff Pickard  | 301-785-6390
Westat<https://www.westat.com/>  |  Facebook<http://www.facebook.com/westat.hq>  |  Twitter<http://twitter.com/Westat>  |  LinkedIn<https://www.linkedin.com/company/westat>

**Comment by rzander** [comment]
That's confusing, but my Win10 has the msxml3x files... it seems you are right :-)

**Comment by GeoffP1501** [comment]
Don’t tell my xwife or my kid… they won’t believe you.

Geoff Pickard  | 301-785-6390
Westat<https://www.westat.com/>  |  Facebook<http://www.facebook.com/westat.hq>  |  Twitter<http://twitter.com/Westat>  |  LinkedIn<https://www.linkedin.com/company/westat>

**Comment by rzander** [comment]
Thx, msxml4x will be removed in V1.0.3.9...

**Comment by rzander** [comment]
Fixed
