### ISSUE TITLE
Can't Use Extracted MSI File - Requires Bootstrapper

### ISSUE THREAD

**Issue by SCCMAdmin** [rzander/sccmclictr#31]
Hi @rzander 

I have 1.0.3.8 EXE and I extracted the contents to a folder using this command:
Client.Center.for.Configuration.Manager_v1.0.3.8.exe /extract:T:\CC2012
All good.

Then I tried to use the 64-bit MSI and I can't. When you try and execute it this error appears:
![image](https://user-images.githubusercontent.com/29601648/30432858-3f301fb6-99a6-11e7-8132-5c3dd65614e7.png)

How do we get around this?

I want to host the MSI as an SCCM application and use command line options per standard to install and configure.

Also, documentation from codeplex shows working with the MSI and I can't do it. Would love to and really need to.

Thanks.

**Comment by SCCMAdmin** [comment]
e.g. command line:
msiexec.exe /i "Client Center for Configuration Manager_v1.0.3.8.x64.msi" /qn /l*v "%windir%\Install_Client_Center_for_SCCM_1.0.3.8_x64.log" CONSOLEEXTENSION=FALSE TRANSFORMS="CCCM_mytransform.mst"

**Comment by sbf-** [comment]
To install the MSI only (without bootstrapper), add SETUPEXEDIR=1 on the msiexec command line
It's case sensitive.

**Comment by SCCMAdmin** [comment]
Hi All, apologies for the silent air. :-)  I logged this issue then went on holidays. I will use the information and report back soon. 

Thanks for your response @sbf- .

**Comment by rzander** [comment]
Fixed when using Parameter SETUPEXEDIR=1
