### ISSUE TITLE
Using EXE in Command Line Has Shortcomings

### ISSUE THREAD

**Issue by SCCMAdmin** [rzander/sccmclictr#32]
Hi @rzander 

I tried to use the EXE in a command line after I had trouble with the MSI and I could not proceed. I found things a little difficult. The command line looks something like this:
Client.Center.for.Configuration.Manager_v1.0.3.8.exe /qn /l*v "%windir%\Install_Client_Center_for_SCCM_1.0.3.8_x64.log" CONSOLEEXTENSION=FALSE TRANSFORMS="CCCM_mytransform.mst"

When the EXE runs, it extracts itself to the elevating user's profile folder and executes from there. This is something that goes out of control of the execution. Let me explain. The transform uses an external SCCMCliCtrWPF.exe.config file as I have customised it. The file works. The file is sitting with the EXE. When the EXE runs it goes to another folder and SCCMCliCtrWPF.exe.config is not in that new folder. This creates a problem. 

Also, the transform file is sitting with the EXE, but is not in the extracted temp path the EXE extracts too. To use the transform a full path needs to be explicitly entered in the command line. This won't work when deploying with SCCM as the cache folder will be a different path every time.

The source folder looks like this:
![image](https://user-images.githubusercontent.com/29601648/30433683-72ebaf94-99a8-11e7-83cb-fae46ed5b2d6.png)
Simple.

When the above command line is run, the working folder is not the source folder and then the EXE which has executed an MSI then complains that the SCCMCliCtrWPF.exe.config file is missing and the transform won't be applied.

What can we do to remediate this?

My answer is that you allow us to use the MSI. See Issue #31. If that issue is solved, this issue becomes obsolete unless someone needs to use the EXE in which case these problems are still valid if that someone is customising SCCMCliCtrWPF.exe.config or the MSI with a transform.

Thanks again.

**Comment by sbf-** [comment]
To install the MSI only (without bootstrapper), add SETUPEXEDIR=1 on the msiexec command line
It's case sensitive.

**Comment by SCCMAdmin** [comment]
Hi All, apologies for the silent air. :-)  I logged this issue then went on holidays. This issue is about the documented use of the EXE. Any response for this?

Thanks for your response @sbf- . This issue is not about the MSI so in this context I will be ignoring your response here (which is useful in the other thread).

We need to decide if the EXE will be used this way or not. If yes, we need a solution. If no, we need to destroy the faulty EXE instructions (or I need to understand them better which is always a possibility and make them work).

**Comment by rzander** [comment]
As defined on Wiki ( https://github.com/rzander/sccmclictr/wiki/3)-Installation ), you have to extract the MSI's from the .exe by using the /extract command.

Once you have the MSI, you can create a custom MST with all your changes... but you have to add the Parameter SETUPEXEDIR=1 on the MSI command line..
