### ISSUE TITLE
Connecting to machines with names only containing numbers fails

### ISSUE THREAD

**Issue by carlitog** [rzander/sccmclictr#33]
When trying to connect to machines which only use numbers for their name e.g. 024445271355 client center fails to connect with error - unable to connect.

The machines are win10 x64, online and firewall disabled. All other win10 machines connect fine.

**Comment by rzander** [comment]
Are you able to connect with PowerShell?
`Enter-PSSession <Computername>`

**Comment by carlitog** [comment]
Hi there, we've found we can connect to machines that only have numbers in
the names using the FQDN.

Connecting fails (in PowerShell remoting) when using just the netbios name.

**Comment by rzander** [comment]
It's not a ClientCenter issue.
