### ISSUE TITLE
SCCM Plugins

### ISSUE THREAD

**Issue by RobNETIT** [rzander/sccmclictr#34]
Hi,

The way that I interpret the Plugin Table @ https://github.com/rzander/sccmclictr/wiki/3)-Installation

I would expect that the following Plugins would work assuming that the SCCM 2012 or later Admin Console is installed:

Plugin_CMRemote.dll ConfigMgr Remote Tools
Plugin_CMResourceExplorer.dll ConfigMgr Resource Explorer
Plugin_StatusMessageViewer.dll ConfigMgr StatusMessage Viewer 

But none of them can be selected. I have tried registering / removing / re-registering Console extensions. I have seen the same behaviour with:

Client Center 1.0.2.0 / SCCM 2012 R2 SP1 CU3 / Windows Server 2012 R2
Client Center 1.0.3.9 / SCCM CB 1706 / Windows Server 2012 R2

Each time I have invoked Client Center by right-clicking the client computer in the SCCM Admin Console and connectivity is successful.

Or is this behaviour to be expected?

Thanks

Rob

**Comment by rzander** [comment]
Have you seen the column "Donator" on the Table -> You need a key to enable this Feature...

**Comment by RobNETIT** [comment]
Yes I had - I misinterpreted the table.

Thanks

Rob

**Comment by rzander** [comment]
Anything I can do to make it more clear? Improvementas are always welcome...

**Comment by RobNETIT** [comment]
Yep.

1. Remove the "CM Console" column altogether
2. Include an * beside the X in the "Donator" column for the plugins that require the SCCM Admin Console to function.
3. Add a Note at the bottom of the table explaining that the SCCM Admin Console needs to be installed for the items marked with an * to function.

Also, maybe I am blind but I could not see how to donate on the Github site.

Thanks

Rob

**Comment by SCCMAdmin** [comment]
Hi @RobNETIT , I can see @rzander has added a Donate button underneath the plugins table that you can click that goes to PayPal. Normally the donate button is within Client Center on the first page once launched. Launch it directly by a click (not via SCCM console) and you should see it. Best wishes.
PS. For me some time back now (with v1.0.1.0) best $10 I ever spent!
