### ISSUE TITLE
Import from catalog list empty

### ISSUE THREAD

**Issue by akukalle** [rzander/sccmclictr#35]
What is requirements to list applications in import from catalog? I have installed client center to two computers. In first one catalog list is populated but in another one it is empty.
I have done testing by connecting same computer and using same user account in both computers.
![image](https://user-images.githubusercontent.com/33147710/32094303-f90eb06e-bb07-11e7-87f1-e3d2621a2150.png)

**Comment by rzander** [comment]
The Application Catalog does only list Applications with a deployment to the user that is running ClientCenter...  
You should see the same applications as if you open the Application Catalog web site:
![image](https://user-images.githubusercontent.com/11909453/32097781-edbf30be-bb0a-11e7-8feb-bc1cbbebae65.png)

**Comment by akukalle** [comment]
Yes I understand that.

On computer where I have the problem catalog web site shows applications but client center does not.

**Comment by rzander** [comment]
In the PowerShell pane, you may have recognized that it get the App Catalog URL from: 
` ([wmiclass]'ROOT\ccm\ClientSdk:CCM_SoftwareCatalogUtilities').GetPortalUrlValue()`

Does this command return the proper URL of your App Catalog Web Service Point?

**Comment by rzander** [comment]
I can not reproduce the Problem; more Information required.
