### ISSUE TITLE
Installing ClickRun setup on Win10 build 1709 w/Controller Folder access fails

### ISSUE THREAD

**Issue by PierreInOttawa** [rzander/sccmclictr#36]
If Controller Folder Access is enabled to protect the public desktop, the Client Center setup will fail.  I had to disable Controller Folder Access to complete the setup.

**Comment by rzander** [comment]
The Setup will create a shortcut on the Desktop.. To disable the shortcut, you have to modify the MSI or create an MST that disables the Desktop Icon... to get the MSI, you have to extract the .exe as defined in: https://github.com/rzander/sccmclictr/wiki/3)-Installation

**Comment by rzander** [comment]
Sorry, have not seen that you mention the ClickOnce Setup and not the Installer... There is currently no Option to prevent the Desktop-Icon on the ClickOnce Setup.

**Comment by PierreInOttawa** [comment]
It’s all good.  Just an observation with the new Controlled Folder feature in build 1709 in case others run into it.  Thank you very much for the response, I’m a big fan of your toolset.
