### ISSUE TITLE
commandline arguments add username/pwd

### ISSUE THREAD

**Issue by claus66** [rzander/sccmclictr#37]
We use weblaps to secure workstations. In order to connect to at machine we have to retrieve pwd for the local admin account through webservice. Can  we open CCCM with hostname,user and pwd as arguments?

**Comment by rzander** [comment]
Currently not... and I'm not sure if it's a good idea to pass a plaintext password as Parameter...  it would be visible in Task-Manager (column CommandLine)... ?!

**Comment by claus66** [comment]
Maybe not - but other remote tools such as dameware supports it - and yes it is visible in task-manager. But still a feature I'd love

**Comment by rzander** [comment]
let's keep this request open, maybe others can vote or comment... I just do not want to invest time into something that is not really needed....

**Comment by claus66** [comment]
Ok - and thanks for looking into it

**Comment by SCCMAdmin** [comment]
Happy New Year All!

@claus66 i like this idea. We use Secret Server (sounds like your tool) to manage local admin passwords. We can authenticate normally (using the fields when connecting through the UI) and don't need the command line. However this would be a nice to have add-on for us (not a requirement). 

Thought I would add here to show the interest and give another environment perspective.

**Comment by rzander** [comment]
V1.0.4.2 will Support `/Username:xxx /Password:xxx`

**Comment by claus66** [comment]
Very nice
Works as wanted
Thanks,
Claus
