### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by theaquamarine** [rzander/sccmclictr#38]
I'm trying to build sccmclictr, and I'm encountering two issues:
- There's a file called Settings.cs referenced in the csproj, under SCCMCliCtrWPF\SCCMCliCtrWPF\Settings.cs, which is missing from git. Is this being in the project a mistake, or is it something that should be present but isn't?
- There's a reference to a customization.dll, where should that be coming from?

Thanks!

**Comment by rzander** [comment]
Settings.cs was missing, it's fixed now.
You can remove all references to Customization.dll as this dll does handle the Donators-Key. Be aware: without  Customization.dll, most of the Plugin's will not work as they are for donators only (https://github.com/rzander/sccmclictr/wiki/3)-Installation#plugins)
