### ISSUE TITLE
Client Center freezes when opening

### ISSUE THREAD

**Issue by bruckect** [rzander/sccmclictr#51]
I'm running version 1.0.3.9 and everytime I launch it, it appears to re-connect to the last computer that I connected to before I closed it. The program is unresponsive for 45 seconds to 2 minutes and then I am able to clear out the computer name field and connect to another PC. Once it "times out" the program operates normally.
Does client center attempt to automatically reconnect to the last PC that it was connected to? If so, can we remove this behavior?

**Comment by rzander** [comment]
Does it really reconnect ? or is just the first startup very slow ?
There is no reconnect in the tool expect if you run the .exe with a hostname as parameter.

If it's starts very slowly then it's mostly the validation of file signature. In most cases I've seen it's an outdated list of root certificates (check if "StarCom Certification Authority" is a trusted root certifacte), or you have enforced to check the CRL ( Certificate Revocation List ) but your client can not reach the CRL Server (e.g. cert.starcom.org, crl.startssl.com, crl.starcomca.com ).

**Comment by bruckect** [comment]
Ah ha! that is likely the case. We do force a CRL check, but the PC i'm running from cannot reach out to those addresses. Thanks for the tip!
