### ISSUE TITLE
Reset Provisioning mode needs adjustment

### ISSUE THREAD

**Issue by AutomanRJJ** [rzander/sccmclictr#54]
Hey there,
Thanks so much for the tool, its awesome!
I just wanted to let you know about that the maintenance/reset provisioning mode needs to be adjusted.  The method used within the quick list does not fully pull the client out of provisioning mode, it just sets the registry of the status to false, but that is just a surface "Status" and altering it does not remove the client fully from the provisioning mode, it must be done with the WMI command.  I have a dos command that I use for it but have not converted it to PowerShell, maybe it will help with the update needed;
%windir%\system32\wbem\wmic.exe /Namespace:\\root\CCM PATH SMS_Client Call SetClientProvisioningMode 0

**Comment by rzander** [comment]
Thanks, will fix that...

**Comment by rzander** [comment]
Fixed in the Library sccmclictr.automation.dll:
https://github.com/rzander/sccmclictrlib/commit/864a8ee04fb10575e07e8c906b93b2f4bbe52790
this change will be implemented in V1.0.4.2
