### ISSUE TITLE
1.0.4.1 Installs to Program Files (x86) and not Program Files

### ISSUE THREAD

**Issue by bruckect** [rzander/sccmclictr#55]
I see in the release notes that you only support 64-bit in this release, but the software only installs to Program Files (x86). Can you update the release so that it will always install to Program Files?

**Comment by rzander** [comment]
I wans't aware of that; so yes, makes sense...

**Comment by bruckect** [comment]
Any ETA on when this could be fixed?

**Comment by rzander** [comment]
it depends.... this year, maybe this month...

**Comment by sbf-** [comment]
You can try this (didn't test it, but in most cases it should work):
Extract the msi by running the setup with `/extract <path>`
Install the msi with (don't forget the double quotes):
`msiexec /i "Client Center for Configuration Manager_v1.0.4.1.msi" SETUPEXEDIR=1 INSTALLDIR="C:\Program Files"`

**Comment by rzander** [comment]
Fixed in V1.0.4.2
