### ISSUE TITLE
Unable to Connect - Windows 10 devices

### ISSUE THREAD

**Issue by Loriden** [rzander/sccmclictr#59]
I've been troubleshooting unable to connect to Win10 machines even though WinRM is configured correctly. I've found that the error the client center is presenting is spurious - running a Enter-PSsession command seperately to the Client Center would give the proper error. 

Once i got down to it - i found that once i ran enter-PSSession the Client Center would then be able to connect, regardless of whether i was in the session or not. 

Still looking into it, but at the very least the error returned by the Client Center is wrong in this scenario. Outside of lvl 1 techs trying to connect over IP without using HTTPS, it appears everything else is working normally, except for when we need to run Enter-PSSession before connecting to Win10 machines.

**Comment by rzander** [comment]
Do I get it right, that you are using an encrypted (SSL) WinRM session ? Any other special WinRM settings in place ?
