### ISSUE TITLE
Deleting an Entry under Execution History with Keyboard is not the same as with Mouse

### ISSUE THREAD

**Issue by bugmelder** [rzander/sccmclictr#6]
If an Entry under Execution History gets deleted with Keyboard then the Entry is only not visible until the Window is reopened.
If an Entry under Execution History gets deleted with Mouse then the Entry is permanent deleted and can be ReRunned under Advertisements.

**Comment by rzander** [comment]
Fix will be part of V1.0.3.5

**Comment by rzander** [comment]
Fixed
