### ISSUE TITLE
suggestion: add date installed to the "All Updates" in Inventory.

### ISSUE THREAD

**Issue by jjlink** [rzander/sccmclictr#62]
Since Microsoft no longer fills out the update Bulletin number there is no longer any way to sort for the latest updates installed. Adding the Installed Date (if the update is installed) will allow us to sort and see the latest installed patches remotely. This is valuable when assessing problems caused by the latest installed patches.

**Comment by rzander** [comment]
The WMI Class to get the installed SW Updates (CCM_UpdateStatus) does not have an InstallDate Property... ROOT\cimv2:Win32_QuickFixEngineering has an Property InstallDate but I do not get any values... I recommend to place a uservoice request for the InstallDate (on CCM_UpdateStatus) on https://configurationmanager.uservoice.com ... If you post the link to your UserVoice, I will give it a vote.

**Comment by jjlink** [comment]
Submitted idea. Thanks
https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/34412434-add-missing-properties-to-win32-quickfixengineerin

**Comment by rzander** [comment]
You can re-open the issue once MS has implemented the installdate in CCM_UpdateStatus...
