### ISSUE TITLE
WinRM issue with Windows 10 computers

### ISSUE THREAD

**Issue by GenBuri** [rzander/sccmclictr#65]
Hello !

We are gradually moving from Win 7 to Win 10 and we can't connect to those windows 10 computers.
The WinRM service is enabled. I tried restarting it, just in case, but it's still not connecting.

Anything else I could try? 

Thank you very much! We love your tool here in Canada!

**Comment by rzander** [comment]
You have to enable PSRemoting… In PowerShell enter:
`Enable-PSRemoting -Force`

**Comment by GenBuri** [comment]
Thank you for your response!
Unfortunately that didn't work. This is what I got :

WinRM is already set up to receive requests on this computer.
WinRM is already set up for remote management on this computer.

**Comment by rzander** [comment]
If WinRM is enabled, try to connect a remote Client with PowerShell: `Enter-PsSession <Computername>`  
  
Do you get an error message ?

**Comment by GenBuri** [comment]
This is what I have. Same thing in the Client Center :

Enter-PsSession : Connecting to remote server wquen13049 failed with the following error message : WinRM 
cannot complete the operation. Verify that the specified computer name is valid, that the computer is 
accessible over the network, and that a firewall exception for the WinRM service is enabled and allows 
access from this computer. By default, the WinRM firewall exception for public profiles limits access to 
remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting 
Help topic.
At line:1 char:1
+ Enter-PsSession wquen13049
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (wquen13049:String) [Enter-PSSession], PSRemotingTransportExc 
   eption
    + FullyQualifiedErrorId : CreateRemoteRunspaceFailed

**Comment by rzander** [comment]
You checked the Firewall? is the Firewall managed by GPO? Do you have a Inbound Rule that allows Port 5985 (Windows Remote Management (HTTP-In)) ?

**Comment by GenBuri** [comment]
It is not managed by GPO. It is managed by our security team.
They are supposed to get back to me on that port question.
