### ISSUE TITLE
not available in Microsoft Store anymore?

### ISSUE THREAD

**Issue by ersatyle** [rzander/sccmclictr#66]
https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=u9Wq2LzJ2k2Vsc4u.0.0.3
We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.
link from the main page doesn't seems to work
https://www.microsoft.com/store/apps/9NBLGGH5127B?ocid=badge

**Comment by rzander** [comment]
MS has removed the Tool from the Store because it requires elevated rights. Thats not really the case because you only need admin rights on the target Client...

**Comment by rzander** [comment]
You can download the APPX from https://github.com/rzander/sccmclictr/releases/tag/1.0.4.1

**Comment by JDvrosky** [comment]
Supercool! Thank you!

**Comment by Niglb** [comment]
This is too bad as I am building out an Admin tools app collection for a project...I can deploy the MSI version of course but using the Store for Business is the goal

**Comment by rzander** [comment]
It's back online (V1.0.6.0)
