### ISSUE TITLE
The WinRM client received an HTTP bad request status (400)

### ISSUE THREAD

**Issue by KelvinLoo1989** [rzander/sccmclictr#68]
Good Day Sir,

I am part of an IT Service Desk and half of my team is having issues trying remoting into our users machine.
Error mentioned in title.

The difference between those working and those not is the type of AD Account that we are using.
Those not working belongs to a set of AD group that grant higher access in the company (Elevated Access)

Seeking your advise on how to troubleshoot this matter. I've tried removing myself an adding our accounts into AD groups that grant lower access but that cant be the fix because that will affect our job scope.

**Comment by rzander** [comment]
Try to connect with PowerShell, to get the full error message: 
PowerShell Command:
`Enter-PSSession -ComputerName <Your Target Host>`
