### ISSUE TITLE
OS Build not showing the extended number

### ISSUE THREAD

**Issue by NarayanasamyB** [rzander/sccmclictr#69]
![build](https://user-images.githubusercontent.com/39905917/40912061-25f43f82-680e-11e8-9333-86c47f0110d7.PNG)

![image](https://user-images.githubusercontent.com/39905917/40912089-3ae6e944-680e-11e8-8b48-ffa6fe3915c8.png)

**Comment by rzander** [comment]
Fixed in https://github.com/rzander/sccmclictr/commit/09747d6efd70f9c6a27e22c412f436d32f7467f1

**Comment by NarayanasamyB** [comment]
It still doesn't work
