### ISSUE TITLE
Register console extensions when installing exe

### ISSUE THREAD

**Issue by theaquamarine** [rzander/sccmclictr#7]
Registering the console extensions when installing using the exe, either by default or as an optional argument, would be really useful and save manually installing them for non-admin users.

**Comment by SCCMAdmin** [comment]
Sounds like a great idea @theaquamarine. I would be interested in the same as an MSI PROPERTY=Value.

**Comment by rzander** [comment]
The MSI Propery "CONSOLEEXTENSION" will allow to control the setup of the extension.  CONSOLEEXTENSION will have a defaut value of TRUE which means it will install per Default. So if you do not want to have the extenseion then set CONSOLEEXTENSION=FALSE

**Comment by theaquamarine** [comment]
Awesome, thanks very much
