### ISSUE TITLE
Windows10 Store App Fails to Install

### ISSUE THREAD

**Issue by wheelermk** [rzander/sccmclictr#70]
Hello,

I attempted to install the Windows 10 Store app, but received the following error message:

Ask the app developer for a new app package. This one isn’t signed with a trusted certificate (0x800B0100)

Thanks,
Martin.

**Comment by rzander** [comment]
Appx is now signed: https://github.com/rzander/sccmclictr/releases/download/1.0.4.1/sccmclictr.appx
