### ISSUE TITLE
Client Center with LAPS (Local Administrator Password Solution)

### ISSUE THREAD

**Issue by john-d-reynolds** [rzander/sccmclictr#73]
We have implemented LAPS a Microsoft tech that essentially forces you to use a local admin account when connecting to and administering domain PCs with a randomly generated PW which is stored in AD.
This is no different than using just a standard local admin account and PW. When I try to connect to machines with this local user and PW in the connection settings I get connection failure:

WinRM cannot process the request. The following error with errorcode 0x80090311 occurred while using Kerberos authentication: There are currently no logon servers available to service the logon request.

This works perfectly if we use a domain account that has local admin rights on the same computer.  Is Client center restricted from using local admin accounts?

Many Thanks indeed
John

**Comment by rzander** [comment]
Are you able to connect with PowerShell directly? e.g. `Enter-PSSession <Hostname>`
I think PowerShell remoting is configured per default to use Kerberos authentication only... Let me know if you can connect woth PowerShell directly....

**Comment by john-d-reynolds** [comment]
Thanks so much for getting back to me.

If I use a command like:

Enter-PSSession -ComputerName WKSXXXXX -Credential WKSXXXXX\administrator

I do get prompted for a password but then get the same output as I did in client center:
[cid:image001.png@01D413B0.53448BC0]

So it’s a limitation of PS?

**Comment by rzander** [comment]
I would not say limitation, as I'm sure that you can change the configuration. But if you enable Basic authentiction without encryption , you may open other doors… So the default configuration and requirement to use Kerberos makes sense in most cases.

**Comment by theaquamarine** [comment]
Normally psremoting uses kerberos, which means a domain account must be used- laps accounts are local, so can't do that. You can set winrm to use https with a trustedhost list, but it's quite a lot of work and not usually worth it/desirable given how powershell remoting works compared to, for example, rdp.

________________________________

**Comment by john-d-reynolds** [comment]
Thanks for your input Roger, you are right this was  limitation of PS Remoting (I maybe should have figured that out myself).

On the very small number of PCs that we use client center on we just needed to enable alternative (NTLM) authentication by trusting the target PCs (or in this case private subnet) like:

Set-Item wsman:\localhost\client\trustedhosts 10.*

Then using the IP or FQDN of the target PC and defining the local username and LAPS pw in connection properties it connects fine.

Many Thanks to you indeed!!
