### ISSUE TITLE
Provide UI hints that disabled plugins need donation to enable

### ISSUE THREAD

**Issue by gunther3613** [rzander/sccmclictr#75]
It is not intuitive that the reason why the Remote Desktop and Remote Assistance plugin buttons are greyed out. 

I thought that the program wasn't working correctly due not having the correct path or something because last time I used this program was three years ago for the SCCM 2007 version. I was intending on forking the program and fixing it with a pull request because these features are going to be a time saver in my current job. 

I am willing to donate if it is clear that something I need is available after donating.

I want to say thank you for the great program.

**Comment by rzander** [comment]
https://github.com/rzander/sccmclictr/wiki/2)-Requirements#free-vs-donators-version

I agree that it can be confusing… I will update the ToolTip text if the Plugin is disabled.
