### ISSUE TITLE
Need to change license information

### ISSUE THREAD

**Issue by perobinson** [rzander/sccmclictr#77]
We are using 1.0.4.25 and our license is under a name of a person that no longer works with our firm. How would I submit a request to change who the SCCMCLICTR is licensed to?

**Comment by rzander** [comment]
You can still use the exiting key as it's not a license, it's a gift for the donator. If you want another name, make a donation (>10$) and you will get another key with the name of the donator.

**Comment by perobinson** [comment]
How do I make a donation? Do you have a link?

Sent from VMware Boxer

On Aug 11, 2018 3:38 AM, Roger Zander <notifications@github.com> wrote:

You can still use the exiting key as it's not a license, it's a gift for the donator. If you want another name, make a donation (>10$) and you will get another key with the name of the donator.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rzander_sccmclictr_issues_77-23issuecomment-2D412260981&d=DwMCaQ&c=Rlm5WhGmPEr8srpDE4r86Q&r=u3UNpMptFmTI1j4FoGzVXo2GpAaV7NKCv7_argC_uT8&m=qlAW9NCqxsAZj6X4hJni5p8JEvBVNtPTjVOntXfKy2I&s=7GqJSHGxD7d2M9Eletg1RvHMZLeXnMHXPen-YlGzgHI&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AoUsYZVoDK9LGayPc44swEwprb-2DASKK4ks5uPpgTgaJpZM4V4wxi&d=DwMCaQ&c=Rlm5WhGmPEr8srpDE4r86Q&r=u3UNpMptFmTI1j4FoGzVXo2GpAaV7NKCv7_argC_uT8&m=qlAW9NCqxsAZj6X4hJni5p8JEvBVNtPTjVOntXfKy2I&s=hNpnouusQJt8Jwqo764WKmNs9-Rho1uG74HR9n3hRSw&e=>.


The preceding email message may be confidential or protected by the attorney-client or work-product privileges. It is not intended for transmission to, or receipt by, any unauthorized persons. If you have received this message in error, please (i) do not read it, (ii) reply to the sender that you received the message in error, and (iii) erase or destroy the message and any attachments or copies. Any disclosure, copying, distribution or reliance on the contents of this message or its attachments is strictly prohibited, and may be unlawful. Unintended transmission does not constitute waiver of the attorney-client privilege or any other privilege. Legal advice contained in the preceding message is solely for the benefit of the Foley & Lardner LLP client(s) represented by the Firm in the particular matter that is the subject of this message, and may not be relied upon by any other party. Unless expressly stated otherwise, nothing contained in this message should be construed as a digital or electronic signature, nor is it intended to reflect an intention to make an agreement by electronic means.

**Comment by rzander** [comment]
There is a Donate button on https://github.com/rzander/sccmclictr. ( direct link:  https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TLTFJHYA69VHU )
