### ISSUE TITLE
Feature Request - same capabilities for Packages as for Applications

### ISSUE THREAD

**Issue by bateskevin** [rzander/sccmclictr#78]
Hi, I love this tool! 

I wondered if it would be possible, to have the same visibility on deploymenets of packages as for applications. For Applications I can see if the App is currently downloading, installing or whatever error it had. For Packages I seem to only be able to see the advertisement. 

Thx for letting me know!

Kevin

**Comment by rzander** [comment]
Hi Kevin,
Client Center can only show informations that the ConfigMgr API provides… Applications and Packages are handled completely different. There is no common API which allows to collect status for Packages and Applications. 

On Packages, you have Events ( Monitoring Node -> Event Monitoring -> Start Monitoring) and the Execution History ( SoftwareDistribution node ). On Application, you only have the status from "Software Summary" (SoftwareDistribution Node).

You may have to open a ConfigMgr UserVoice request to get an API which provides more information: https://configurationmanager.uservoice.com

I don't thin I can help here...

**Comment by bateskevin** [comment]
Hey rzander,

Thanks for the quick reply. Alright. I've submitted the Idea. I'm gonna close the issue and reopen it if I get Feedback on my uservoice entry.

cheers!
