### ISSUE TITLE
Request to add another native remote control application

### ISSUE THREAD

**Issue by kintaroju** [rzander/sccmclictr#8]
Hi Roger,

You have a great product that you wrote, as a enhancement could you add a piece of code to allow to remote into a computer with Remote Assistance as well as I know you have one for RDP, and the native SCCM Remote Tool, that would complete the Microsoft list of remote session tools :D.

it'll be just as a simple command of "msra /offerRA %comptuername%".

Cheers

**Comment by SCCMAdmin** [comment]
Minus the typo, I second this idea too. Nice one @kintaroju !

Having the trifecta of Microsoft tools as you say, would actually replace an internal application that was created (not by me) to invoke such things. I think sccmclictr could replace it almost entirely (we have some other functionality that talks to SCCM server that I don't believe is the intent of sccmclictr).

Nice work for suggestion and I'm sure upcoming aced enhancement by the master himself. :-) 👍

**Comment by rzander** [comment]
First draft version (copy into the same dir as SCCMCliCtrWPF.exe):
[Plugin_MSRA.zip](https://github.com/rzander/sccmclictr/files/1106742/Plugin_MSRA.zip)

**Comment by kintaroju** [comment]
Hi @rzander ,

I copied the dll into the folder where that exe is, except I don't see an icon anywhere for it, do i need to modify anything to make it appear?

Cheers

**Comment by rzander** [comment]
You should get an Icon "CustomAction" and "Agent Actions\Tools":
![image](https://user-images.githubusercontent.com/11909453/27672928-4aa8a0ec-5c9e-11e7-890c-7c5ffff029e5.png)
![image](https://user-images.githubusercontent.com/11909453/27672951-620bc052-5c9e-11e7-9a5e-bd05227658d7.png)

**Comment by kintaroju** [comment]
Hi @rzander ,

I've attached a copy of the screen shot to indicate the version I am running and the location of the DLL, even for the heck of it i even did the installation on a clean VM, and no luck. my configuration is Windows 7 Enterprise x64

![capture](https://user-images.githubusercontent.com/29717036/27711841-4e1a402e-5cd9-11e7-928c-6fde5118d9a3.PNG)

![capture 2](https://user-images.githubusercontent.com/29717036/27711898-7cc42020-5cd9-11e7-8f4f-3a2bae407894.PNG)

Let me know if you want me to test anything else 

Cheers!

**Comment by rzander** [comment]
No Idea why you do not get the Icon.. but based on the screenshot, I see that you do not have the donator Version... you may see the Icon in the future but it will be disabled as this is a "Donator"-only Feature...

Will integrate the addin in V1.0.3.6

**Comment by kintaroju** [comment]
Hi @rzander ,

I have a validate donator key and applied, still doesn't work. 

Hopefully a recompile with 1.0.3.6 will fix it :D 

Cheers,
Jon

**Comment by rzander** [comment]
I've update the Click-Once to V1.0.3.6 ( http://sccmclictr.azurewebsites.net/ClickOnce/ ) and I get the Icon :-)

**Comment by kintaroju** [comment]
Hi @rzander ,

Let me know when you generate the EXE/MSI installer, as my corporate firewall prevents me to do the clickonce installer :( *sniff.

Cheers!

**Comment by kintaroju** [comment]
Hi @rzander ,

Just had a moment to do the offline installer, worked like a charm. Side note i had to remove the dll first before reinstalling to have msra to appear, but thanks for the hard work on this!

Cheers!
