### ISSUE TITLE
DCM Baselines not showing

### ISSUE THREAD

**Issue by Henrikcj** [rzander/sccmclictr#81]
After SCCM CB 1806, DCM baselines is not showing anything. But on the SCCm client in controlpanel it display the baselines fine.

**Comment by rzander** [comment]
This is a ConfigMgr "Bug"... In a remote PowerShell Session, you cannot query the DCM WMI class anymore
`get-wmiobject -query "SELECT * FROM SMS_DesiredConfiguration" -namespace "ROOT\ccm\dcm"`
it will return an error:
`get-wmiobject : Generic failure
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand`

If you are logged on on the target device with the same account as in the remote powerShell session, everything is working...

**Comment by Henrikcj** [comment]
So i need to logon the device with the same account ?
I hope they change that. That dont make any sence. Is that because of a security issue ?

**Comment by rzander** [comment]
No, but during troubleshooting most of my devices worked fine.. because I was already logged on... Just for Information.

**Comment by rzander** [comment]
Problem fixed with ConfigMgr 1810...

**Comment by Henrikcj** [comment]
Hey. I still have that issue on 1810...

**Comment by rzander** [comment]
Is the ConfigMgr Agent on the target Machine also updated (Version >= 5.00.8740.1012 ) ?

**Comment by Henrikcj** [comment]
Yes, the client is updated to that version.

**Comment by Henrikcj** [comment]
My bad... some other admin had removed all baseline on the test envoriment. 
It works now. Sorry for the mistake.
