### ISSUE TITLE
Inventory Data Displays Incorrect Time (UTC Offset)

### ISSUE THREAD

**Issue by SCCMAdmin** [rzander/sccmclictr#83]
Hi @rzander , similar to past issues #20 and #25 I've found another one. :-( Sorry I know this is boring but it matters when troubleshooting to have the correct data in front of you.

In v1.0.4.2 connect to a remote PC, go to Inventory data, pull an adhoc inventory like LastHWinv (you can really use any time, there are many examples) and for me the time is in the future by 11hrs. This exactly matches my UTC offset which is GMT+11.

It would great if this can be corrected for all returned results to show the true date time stamp. Thanks as always.

**Comment by rzander** [comment]
Inventory data is now using Get-CimInstance
