### ISSUE TITLE
Target Computer Ping

### ISSUE THREAD

**Issue by newwolf** [rzander/sccmclictr#84]
Hee, I love your great to and I'm using almost every day.

But would be nice if you can make a little change.
When you open the tool you can enter the Target Computer, but i'm not always sure if it's online.
After that there comes a ping button.
Can you make that appear from the beginning?
And is it olso possible to not hide this bar? So you switch quicker from clients?

Thanks already for making my work that much easier.

**Comment by SCCMAdmin** [comment]
@rzander to confirm, this is coming in 1.0.5.0?  Thanks.

**Comment by rzander** [comment]
yes, it's in 1.0.5.0 ...

**Comment by pilgi3** [comment]
@rzander sorry but i have to contradict. After press "connect" the connection bar with the ping button dissappears. In the configuration the value is "true". Installed version 1.0.5.2.

**Comment by rzander** [comment]
I agree, it's still missing or dropped in 1.0.5.2 .... I will fix it in the next release.
