### ISSUE TITLE
the tools plugin has stopped working..

### ISSUE THREAD

**Issue by russr123** [rzander/sccmclictr#85]
![image](https://user-images.githubusercontent.com/20584235/50592532-7e4bee00-0e62-11e9-8d53-e735b666a9d6.png)

all grayed out

**Comment by rzander** [comment]
If the Donator-Key is missing, it will disable all Plugins… Are you using the MSIX/APPX or ClickToRun Version ?

**Comment by mtk123** [comment]
Also an issue for me and I use the ClickToRun version.  Seems to happen about this time every year. 
![image](https://user-images.githubusercontent.com/46354428/50652456-2b4e6580-0f4c-11e9-9c23-f853eeca60e6.png)

**Comment by russr123** [comment]
ClickToRun Version, and as above, same thing happened jan. 2018...

**Comment by rzander** [comment]
I can confirm, ClickToRun Trial has expired.

**Comment by mtk123** [comment]
Is the plan to fix this for 1.0.4.2 ClickOnce version?  Will there be a ClickOnce for 1.0.5.0? If so, will the AddOns be included and work?

**Comment by rzander** [comment]
V1.0.5.0 is online as ClickOnce. Donator goodies are available until June 2019.
