### ISSUE TITLE
Suggestion: Menu buttons and options

### ISSUE THREAD

**Issue by russr123** [rzander/sccmclictr#86]
Since the windowupdate.log is near useless now in win10, may i suggest you add a button next to it to open the SCCM UpdatesDeployment.log and maybe the WUAHandler.log

in the old V2 version, it was nice that you could edit shortcuts to add your own, if we cant do that, can you add these?
some things still dont work in remote powershell, so still having a PSEXEC launch link is nice.. as well as direct jumps to the 2 logs folders you need to access the most.. and a WOL link would be nice as well

![image](https://user-images.githubusercontent.com/20584235/50696946-d1fb3a80-100e-11e9-9830-ae3f52c8b555.png)

also, if interested in including more scripts, this is a list of what i have in my drop menu..
i can upload or drop a link if needed..

CanProgramRunNow.ps1
CanUpdateRunNow.ps1
CertCheck-PKI.ps1
CertCheck.ps1
CHK-PCnameVSSN.ps1
Count missing updates.ps1
DEL-AllUserTemp.ps1
DEL_local_expired_Certsv2.ps1
FILE Check-SFD.ps1
FIX-BranchCache.ps1
FIX-ConsoleOpenErrors.ps1
FIX-IsCacheCopyNeededERROR.ps1
Fix-remoteComIssues.ps1
FIX-RemoveSGLock.ps1
FIX-StuckBITSJobs.ps1
Fix-TemporaryProfile.ps1
FIX-WindowsUpdate-FIXIT.ps1
FIX-WindowsUpdate.ps1
FIX-WMI.ps1
FIX-WUAandMWerros.ps1
FORCE SCCM Reinstall.ps1
Free disk space.ps1
Generate_WindowsUpdateLog.ps1
Get AD Site.ps1
Get IP.ps1
Get last installed updates.ps1
Get logged on user.ps1
Get Model.ps1
Get OS Version.ps1
Get user OST Size.ps1
Get PowerShell Version.ps1
Get User DIR Size.ps1
Get-BatteryStats.ps1
Get-LastReboot.ps1
Get-PendingReboot.ps1
GET-WSUScontentInfo.ps1
GPUpdate.ps1
Install all mandatory updates.ps1
Location Service Refresh.ps1
Logoff All Users.ps1
Notify-UserOfReboot.ps1
Notify-UserOfUpdates.ps1
Restart enforced-60s.ps1
Restart enforced.ps1
RestartCCMEXEC.ps1
RestartCCMSetUP.ps1
RUN-HealthTask.ps1
SCCM health task install.ps1
SCCM-AutoUpdate.ps1
SCCM-CertCheck.ps1
SCCM-force-install-of-software-updates.ps1
SCCM-Repair.ps1
SCCM-Reset GUID.ps1
SCCM-ResetInventory.ps1
SCCM-RetryTASK.ps1
SCCM-UNINSTALL-REINSTALL.ps1
SCCM-UpateScan.ps1
SCCM-UpdateTASK.ps1
SCCMWINUpdateForce.ps1
SET-WorkingHours.ps1
UpdateComplianceAndRun.ps1
WindowsUpdate and DeliveryOptimization settings.ps1
WOL-Enable.ps1
WSUSForce.ps1

**Comment by SCCMAdmin** [comment]
I'm interested in the scripts too. I do think to myself though, wow, so many scenarios to be rectified. I don't have that many issues that need all these fixes. :-)

Is there some sort of repository folder we can make and share our community scripts in a big pool? For the most part, we are all admins of our environments and pooling resourcing and skills would make sense for the greater good. Perhaps a new item can be opened for this idea.

e.g. I recently coded a PS1 to remove SCCM 2012 clean up the entire OS and then install SCCM CB agent without any OS restart required. Very useful for servers. This was an evolved script from some workstation SOE work I had already working. So two scripts there already to share, although for specific purposes can easily be evolved.

**Comment by rzander** [comment]
If you want to share your PowerShell Scripts, you can upload these here: https://github.com/rzander/sccmclictr/tree/master/Plugins/Plugin_PSScripts/PSScripts or make a .zip and upload it to this thread and I will integrate them into the source repository…

**Comment by rzander** [comment]
Opening UpdatesHandler.log is implemented in https://github.com/rzander/sccmclictr/commit/53af95b62634fd4a4e1b8174c9930a3c34e0a634

**Comment by SCCMAdmin** [comment]
I actually watch WUAHandler.log and UpdatesDeployment.log relatively religiously.

**Comment by rzander** [comment]
So you would also like WUAHandler.log ?

**Comment by rzander** [comment]
Explore Shares plugin is updated to open ccmsetup\logs and ccm\logs

[Plugin_Explorer.zip](https://github.com/rzander/sccmclictr/files/2745012/Plugin_Explorer.zip)

**Comment by russr123** [comment]
added scripts here, it wont me upload them to the link, "File uploads require push access to this repository."

NOTE... some of the "install" scripts the user will need to edit to their local file servers.


[NewScripts.zip](https://github.com/rzander/sccmclictr/files/2746376/NewScripts.zip)

**Comment by russr123** [comment]
also, these all work great your Collection Commander program as well :)

**Comment by rzander** [comment]
Thans @russr123 , the files are now uploaded to https://github.com/rzander/sccmclictr/tree/master/Plugins/Plugin_PSScripts/PSScripts

**Comment by SCCMAdmin** [comment]
WUAHandler.log, yes please @rzander

**Comment by rzander** [comment]
Button to open WUAHandler.log is now implemented

**Comment by rzander** [comment]
Attached the binaries for an V1.0.5.0 Preview:
[Preview1.0.5.0.zip](https://github.com/rzander/sccmclictr/files/2753280/Preview1.0.5.0.zip)

**Comment by newwolf** [comment]
Just updated the preview, but the list is a little bit huge. ;)
Is it possible to categories the scripts so it is more indexed?

**Comment by russr123** [comment]
> Just updated the preview, but the list is a little bit huge. ;)
> Is it possible to categories the scripts so it is more indexed?

the 1 problem i ran into tying that, it it puts all folders at the bottom of the list :(

**Comment by russr123** [comment]
> Button to open WUAHandler.log is now implemented

i oopsed in the 1st post, should be UpdatesDeployment.log NOT Updateshandler.log..... the handler log sucks :)

**Comment by newwolf** [comment]
Just interested, but is there a ETA for V1.0.5.0 milestone ???

**Comment by rzander** [comment]
I was in the hope that someone will organize the custom PowerShell scripts in a folder structure…  :-)
It's close... but give me some days to test the current build…

**Comment by newwolf** [comment]
I am quite new with github, but will have a look. :)

**Comment by newwolf** [comment]
> 
> 
> I am quite new with github, but will have a look. :)

Just updated it and synced, but what's next?
Got a Access denied from Git.

**Comment by rzander** [comment]
V1.0.5.0 preview (as Zip) is available: https://github.com/rzander/sccmclictr/releases/tag/1.0.5.0
@newwolf I've already created some Folders in PSScripts. If you have a more granular structure, just upload a .zip with your files here...
