### ISSUE TITLE
Eventvwr

### ISSUE THREAD

**Issue by newwolf** [rzander/sccmclictr#87]
Hey,
Is it possible to add EventViewer to the tools menu just like regedit?
Thanks,
Jos

**Comment by rzander** [comment]
There is a Plugin for "ComputerManager", which contains EventViewer.... 
![image](https://user-images.githubusercontent.com/11909453/50783511-67b2f600-12ab-11e9-9265-59b2c1cb6236.png)

**Comment by newwolf** [comment]
Hmm, ok never thought of that. :)
