### ISSUE TITLE
Import App from Catalog 

### ISSUE THREAD

**Issue by dkjones9602** [rzander/sccmclictr#88]
This may something we did but the Import App from Catalog stopped working. It does list all the apps. But when you pick one and click the Import button, nothing ever happens. It seemed to line up with upgrading the Client Center about 3 or 4 versions ago but it could just as easily be something we did or an upgrade in SCCM that changed something. What should we be looking for to troubleshoot this? thanks again, 
Dave Jones, contributor

**Comment by thecatdidit** [comment]
We have been having the same issue. The last couple of releases, it seems hit or miss. In one case, I removed the ConfigMgr plugin, cleaned up some remnant files and did a reinstall. That fixed it. 

In your %APPDATA% folder (for the account running the plugin), you may find some RZ4CM.exe.xxx.dmp files that could be used for analysis.

**Comment by dkjones9602** [comment]
EXCELLENT!!  Working now. thank you Roger.

**Comment by dkjones9602** [comment]
You have to import and then click Reload Applications again for it to show
up.

I have a couple of questions about this.
1. Obviously, this is just in the computers WMI and not adding a computer
to a collection.  Is there a way to remove it later, sort of un-import it?
2. Will they always be 'Available' and not 'Required' (start installing
immediately)?
3. Is there a corresponding PowerShell command for this?

**Comment by rzander** [comment]
Yes, that's what I mentioned, it may take a while... the process if defined here: https://rzander.azurewebsites.net/how-to-inject-application-policies/

1) if the Agent is not removing them automatically, you can run a "Reset Polcy" with ClientCenter. 
2) Software from the ApplicationCatalog is always available. I've tried to implement an auto trigger, but timing is difficult... it may be easier if you trigger it once it's visible
3) No
