### ISSUE TITLE
Add custom computer shares to "Explore Shares" menu

### ISSUE THREAD

**Issue by CalderX** [rzander/sccmclictr#92]
Hi!

Is it possible to add custom shares to the menu "Explore Shares"?

We have for example our corporate logs in C:\Windows\Logs\Software.

It would have been nice to add such computer-shares or other in the future, maybe in xml?

Greetings

Calle

**Comment by rzander** [comment]
Will be part of V1.0.5.0 ... 
Preview Plugin:
[Plugin.zip](https://github.com/rzander/sccmclictr/files/2800013/Plugin.zip)

**Comment by CalderX** [comment]
Thanks for the plugin but when I putting in new values in the Plugin_Explorer.dll.config it not show in Client Center menu?

I added: <string><string>C$\Windows\Logs\Software</string>


<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="AgentActionTools.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <applicationSettings>
        <AgentActionTools.Properties.Settings>
            <setting name="Folders" serializeAs="Xml">
                <value>
                    <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <string>C$\Windows\Temp</string>
			<string>C$\Windows\Logs\Software</string>
                    </ArrayOfString>
                </value>
            </setting>
        </AgentActionTools.Properties.Settings>
    </applicationSettings>
</configuration>

**Comment by rzander** [comment]
Ooops, the values from the config file are not loaded..

**Comment by rzander** [comment]
Fixed...
[Plugin_Explorer.zip](https://github.com/rzander/sccmclictr/files/2804671/Plugin_Explorer.zip)
