### ISSUE TITLE
1.0.5.0 - Install Date sorted wrong

### ISSUE THREAD

**Issue by newwolf** [rzander/sccmclictr#96]
Hee,

I just did a "inventory" of "installed software" and did a sort on "install date"
But it's sorting on day-month-year.
Is it possible to fix this so it's sorting like year-month-day ?

Greetz,
Jos

**Comment by rzander** [comment]
Fixed in sccmclictr.automation.dll
[sccmclictr.automation.dll.zip](https://github.com/rzander/sccmclictr/files/2850410/sccmclictr.automation.dll.zip)

**Comment by rzander** [comment]
Fixed: https://github.com/rzander/sccmclictr/releases/tag/1.0.5.2
