### ISSUE TITLE
1.0.5.0 Regedit doesn't open remote machine

### ISSUE THREAD

**Issue by realkazman2000** [rzander/sccmclictr#97]
Remote tool for regedit doesn't open remote clients registry.

**Comment by rzander** [comment]
Do you know a way how to open regedit to connect a remote client ?

**Comment by realkazman2000** [comment]
I found this but I am not sure if it will still work..

https://stackoverflow.com/questions/34030813/open-regedit-on-a-remote-workstation

Maybe it might work still..

**Comment by rzander** [comment]
Sending Key-Strokes requires an english version of regedit.  Maybe something for https://wpdev.uservoice.com/ ?!

**Comment by rzander** [comment]
Problem on regedit side...
