### ISSUE TITLE
v1.0.5.0 Does not read SCCMCliCtrWPF.exe.config

### ISSUE THREAD

**Issue by claus66** [rzander/sccmclictr#98]
Default settings are no longer read. We use exclusive WinRM over SSL so this is a major issue for us:
           ` <setting name="WinRMPort" serializeAs="String">
                <value>5986</value>
            </setting>
            <setting name="WinRMSSL" serializeAs="String">
                <value>True</value>
            </setting>`

**Comment by rzander** [comment]
I can not reproduce your issue… Are you copy an "old" config File over the new one ?

**Comment by claus66** [comment]
My bad - uninstalled and reinstalled - and now it works!
Thanks
