### ISSUE TITLE
MSIX Package is not packaged correctly.

### ISSUE THREAD

**Issue by RowdyChildren** [rzander/sccmclictr#99]
The MSIX package needs the runFullTrust capability added because it specifies it is a full trust application

`he path (/p) parameter is: "\\?\D:\users\v-rilchi\Downloads\Client.Center.for.Configuration.Manager-x64.msix"
The output directory (/d) parameter is: "\\?\D:\Temp2"
Unpacking "\\?\D:\users\v-rilchi\Downloads\Client.Center.for.Configuration.Manager-x64.msix" (package name) to "\\?\D:\Temp2" (output directory).
MakeAppx : error: Error info: error 80080204: App manifest validation error: Line 8, Column 6, Reason: The element specified requires "runFullTrust" capability.
MakeAppx : error: Package extraction failed.
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.`

**Comment by Ebag333** [comment]
Without it you get this error:
https://i.imgur.com/WrtiVJ8.png

Being run on vanilla Win10 Pro (10.0.17763 Build 17763) in the screenshot above.

**Comment by rzander** [comment]
Sorry, the MSIX referenced in the APPINSTALLER was the correct one… no idea where the corrupt one came from. The MSIX should now be fixed...
